/**
 * Character map for the app's own Simplified Chinese labels.
 *
 * The components carry a few hundred inline Chinese strings ("房", "卫浴", "步骤 1 / 4"…) written in
 * Simplified. Articles and project text get proper Traditional copies at build time; for these small
 * labels a character-level map is enough, and it is tiny — only the characters that actually occur in
 * the source. The HantText component applies it to text nodes when the language is zh-TW.
 *
 * Run: npx tsx scripts/gen-hant-chars.ts   (also runs in `npm run build`)
 */
import fs from 'fs';
import path from 'path';
// @ts-ignore — no types shipped
import * as OpenCC from 'opencc-js';

const ROOT = process.cwd();
const OUT = path.join(ROOT, 'src', 'data', 'hantChars.generated.ts');
const toTw: (t: string) => string = (OpenCC as any).Converter({ from: 'cn', to: 'tw' });

const walk = (dir: string): string[] => fs.readdirSync(dir, { withFileTypes: true }).flatMap(e => {
  const p = path.join(dir, e.name);
  if (e.isDirectory()) return e.name === 'data' ? [] : walk(p);
  return /\.tsx?$/.test(e.name) && !/translations|faqTranslations|translator|generated/.test(e.name) ? [p] : [];
});
const chars = new Set<string>();
for (const f of walk(path.join(ROOT, 'src'))) for (const ch of fs.readFileSync(f, 'utf8').match(/[一-鿿]/g) || []) chars.add(ch);
const map: Record<string, string> = {};
for (const ch of [...chars].sort()) { const t = toTw(ch); if (t && t !== ch) map[ch] = t; }
fs.writeFileSync(OUT, `// GENERATED by scripts/gen-hant-chars.ts — do not edit by hand.
// Simplified → Traditional for the ${Object.keys(map).length} characters (of ${chars.size} used in the components) that differ.
export const HANT_CHARS: Record<string, string> = ${JSON.stringify(map)};
const RE = new RegExp('[' + Object.keys(HANT_CHARS).join('') + ']', 'g');
/** Convert the app's inline Simplified labels to Traditional, character by character. Idempotent. */
export const toHantText = (s: string): string => RE.test(s) ? s.replace(RE, c => HANT_CHARS[c] || c) : s;
`, 'utf8');
console.log(`[gen-hant-chars] ${Object.keys(map).length}/${chars.size} characters mapped -> ${path.relative(ROOT, OUT)}`);
