// GENERATED by scripts/build-articles.ts from content/articles/*.md — do not edit by hand.
import type { BlogArticle } from '../types';

export const GENERATED_ARTICLES: BlogArticle[] = [];

export const GENERATED_ZH_ARTICLES: Record<string, BlogArticle> = {};
