// GENERATED by scripts/gen-project-facts.ts from the developer sales kits — do not edit by hand.
// Real key features, facilities and nearby places per project, keyed by the id in projectsFallback.json.

export interface ProjectFacts {
  source: string;
  keyFeatures: string[];
  facilities: string[];
  nearby: { category: string; name: string; distance?: string }[];
}

export const PROJECT_FACTS: Record<string, ProjectFacts> = {
 "aricia": {
  "source": "Developer sales kit (2026-08-22)",
  "keyFeatures": [],
  "facilities": [
   "Entrance",
   "Waiting Lounge",
   "Lift Lobby",
   "Management Office",
   "Space for Taska",
   "Shuttle Vehicle Service",
   "50m Infinity Swimming Pool",
   "Sunken Wet Lounge",
   "Jacuzzi",
   "Pool Deck",
   "Wading Pool",
   "Cabana",
   "Seating Lounge",
   "Covered Walkway",
   "Parcourse",
   "Reflexology Path",
   "Play Lawn",
   "Children's Playground",
   "BBQ Deck & Dining Area",
   "Pre-Function Deck",
   "Pocket Garden",
   "Gymnasium",
   "Indoor Play Gym",
   "Badminton Court / Pickleball Court / Multi-Purpose Hall",
   "Hoop Court",
   "Nursing Room",
   "Changing Room",
   "Music Lounge",
   "Outdoor Deck",
   "Games Room",
   "Co-Working Lounge",
   "Function Room",
   "Surau (Female)",
   "Surau (Male)"
  ],
  "nearby": [
   {
    "category": "Public Transportation",
    "name": "LRT Chan Sow Lin",
    "distance": "1.3km"
   },
   {
    "category": "Public Transportation",
    "name": "MRT Chan Sow Lin",
    "distance": "1.6km"
   },
   {
    "category": "Highways",
    "name": "MEX Expressway",
    "distance": "3km"
   },
   {
    "category": "Highways",
    "name": "SALAK Expressway",
    "distance": "3km"
   },
   {
    "category": "Highways",
    "name": "Sungai Besi Expressway",
    "distance": "5km"
   },
   {
    "category": "Highways",
    "name": "MRR2",
    "distance": "7km"
   },
   {
    "category": "Highways",
    "name": "Federal Highway",
    "distance": "7km"
   },
   {
    "category": "Highways",
    "name": "AKLEH Highway",
    "distance": "8km"
   },
   {
    "category": "Shopping Malls",
    "name": "IKEA Cheras",
    "distance": "2.4km"
   },
   {
    "category": "Shopping Malls",
    "name": "MyTOWN Shopping Centre",
    "distance": "2.7km"
   },
   {
    "category": "Shopping Malls",
    "name": "Sunway Velocity Mall",
    "distance": "2.8km"
   },
   {
    "category": "Shopping Malls",
    "name": "AEON Mall Taman Maluri",
    "distance": "3.2km"
   },
   {
    "category": "Shopping Malls",
    "name": "LaLaport Bukit Bintang City Centre",
    "distance": "3.4km"
   },
   {
    "category": "Shopping Malls",
    "name": "Berjaya Times Square",
    "distance": "3.8km"
   },
   {
    "category": "Shopping Malls",
    "name": "The Exchange TRX",
    "distance": "4.3km"
   },
   {
    "category": "Shopping Malls",
    "name": "Pavilion KL",
    "distance": "5.8km"
   },
   {
    "category": "Medical",
    "name": "Sunway Medical Centre Velocity",
    "distance": "3.7km"
   },
   {
    "category": "Medical",
    "name": "Tung Shin Hospital",
    "distance": "4.9km"
   },
   {
    "category": "Medical",
    "name": "Prince Court Medical Centre",
    "distance": "5.4km"
   },
   {
    "category": "Education",
    "name": "Imperium International College",
    "distance": "1.4km"
   },
   {
    "category": "Education",
    "name": "Sunway College @ Velocity",
    "distance": "2.6km"
   },
   {
    "category": "Education",
    "name": "Alice Smith International School",
    "distance": "3.0km"
   },
   {
    "category": "Education",
    "name": "Tsun Jin High School",
    "distance": "4.0km"
   },
   {
    "category": "Recreation",
    "name": "The Royal Selangor Golf Club",
    "distance": "4.1km"
   },
   {
    "category": "Recreation",
    "name": "KLCC Park",
    "distance": "5.1km"
   }
  ]
 },
 "aurum-business-centre-suites": {
  "source": "Developer sales kit (2026-08-10)",
  "keyFeatures": [
   "Versatile Layouts adaptable for home, office, or both",
   "Exclusive Lift Lobby Experience with 5 lifts serving only 10 suites per floor",
   "Light-filled Interiors with 2.6m height windows",
   "Natural Ventilation in all rooms and bathrooms",
   "Multi-tier Security."
  ],
  "facilities": [
   "Podium Lobby",
   "Pantry",
   "Games Lounge",
   "Changing Room",
   "Lifestyle Pavilion",
   "50m Lap Pool",
   "Wading Pool",
   "Water Sculpture Archway",
   "Cabanas",
   "Pickleball Court",
   "Co-Working Space",
   "Feature Spiral Stairs",
   "Gym",
   "Washroom"
  ],
  "nearby": [
   {
    "category": "Public Transport",
    "name": "MRT Taman Naga Emas"
   },
   {
    "category": "Public Transport",
    "name": "LRT Bukit Jalil"
   },
   {
    "category": "Public Transport",
    "name": "LRT Sri Petaling"
   },
   {
    "category": "Public Transport",
    "name": "Terminal Bersepadu Selatan (TBS)"
   },
   {
    "category": "Commercial",
    "name": "Sri Petaling Commercial Hub"
   },
   {
    "category": "Commercial",
    "name": "Kuchai Entrepreneurs Park"
   },
   {
    "category": "Shopping",
    "name": "Pavilion Bukit Jalil"
   },
   {
    "category": "Shopping",
    "name": "Mid Valley Megamall"
   },
   {
    "category": "Shopping",
    "name": "Sunway Velocity"
   },
   {
    "category": "Shopping",
    "name": "IKEA Cheras"
   },
   {
    "category": "Shopping",
    "name": "MyTOWN Shopping Centre"
   },
   {
    "category": "Shopping",
    "name": "Kuala Lumpur City Centre (KLCC)"
   },
   {
    "category": "Education",
    "name": "SK Bandar Baru Sri Petaling"
   },
   {
    "category": "Education",
    "name": "SJK (C) La Salle"
   },
   {
    "category": "Education",
    "name": "SMK Bandar Baru Sri Petaling"
   },
   {
    "category": "Education",
    "name": "International Medical University",
    "distance": "IMU"
   },
   {
    "category": "Education",
    "name": "Bukit Jalil Sports School"
   },
   {
    "category": "Education",
    "name": "SJK (C) Lai Meng"
   },
   {
    "category": "Education",
    "name": "Asia Pacific University (APU)"
   },
   {
    "category": "Healthcare",
    "name": "IMU Healthcare"
   },
   {
    "category": "Healthcare",
    "name": "Universiti Kebangsaan Malaysia Medical Centre",
    "distance": "HUKM"
   },
   {
    "category": "Healthcare",
    "name": "Sunway Medical Centre Velocity"
   },
   {
    "category": "Healthcare",
    "name": "Pantai Hospital Kuala Lumpur"
   },
   {
    "category": "Healthcare",
    "name": "Sunway Medical Centre"
   },
   {
    "category": "Healthcare",
    "name": "Subang Jaya Medical Centre"
   },
   {
    "category": "Recreation",
    "name": "Commonwealth Hill"
   },
   {
    "category": "Recreation",
    "name": "Bukit Jalil Recreational Park"
   },
   {
    "category": "Golf Club",
    "name": "Bukit Jalil Golf & Country Resort"
   },
   {
    "category": "Highway",
    "name": "East-West Link Expressway"
   },
   {
    "category": "Highway",
    "name": "KL-Seremban Highway"
   }
  ]
 },
 "avantro-residences": {
  "source": "Developer sales kit (2026-08-03)",
  "keyFeatures": [],
  "facilities": [
   "Swimming Pool / Infinity Lap Pool",
   "Wading Pool / Water Play Pool",
   "Jacuzzi",
   "Sun Lounges & Pool Terrace",
   "Gymnasium & Workout Deck",
   "Pet Zone / Pet-Friendly Area",
   "Outdoor Playset & Parcourse Playground",
   "Kids' Playground & Playroom",
   "Games Room",
   "Study Room",
   "Co-Working Room",
   "Function Rooms",
   "Multipurpose Hall (Half Basketball / Badminton Court)",
   "BBQ Area",
   "EV Charging Provision",
   "Car Wash Bay"
  ],
  "nearby": [
   {
    "category": "Nearby",
    "name": "Kinrara BK5 LRT Station",
    "distance": "180m"
   },
   {
    "category": "Nearby",
    "name": "Giant Kinrara",
    "distance": "100m"
   },
   {
    "category": "Nearby",
    "name": "KPJ Kinrara Hospital",
    "distance": "200m"
   },
   {
    "category": "Nearby",
    "name": "Tzu Chi International School",
    "distance": "4km"
   },
   {
    "category": "Nearby",
    "name": "Pavilion Bukit Jalil",
    "distance": "4km"
   },
   {
    "category": "Nearby",
    "name": "SJK(C) Lai Meng",
    "distance": "5km"
   },
   {
    "category": "Nearby",
    "name": "IOI Mall Puchong",
    "distance": "5km"
   },
   {
    "category": "Nearby",
    "name": "Sunway Medical Centre",
    "distance": "6km"
   },
   {
    "category": "Nearby",
    "name": "International Medical University (IMU)",
    "distance": "6km"
   },
   {
    "category": "Nearby",
    "name": "Kinrara Golf Club & Resort",
    "distance": "2km"
   },
   {
    "category": "Nearby",
    "name": "Bukit Jalil Highway, KESAS Highway, LDP Highway, MEX Highway, NPE Highway"
   }
  ]
 },
 "ayanna": {
  "source": "Developer sales kit (2026-08-20)",
  "keyFeatures": [],
  "facilities": [
   "Drop-off Lobby - Tower A & B",
   "Water Feature",
   "Interactive Stream",
   "Cabana",
   "Fitness Area",
   "Parcourse Station",
   "Multi-generational Play Area",
   "Pet Play Area",
   "Landscape Staircase",
   "Pet shower area",
   "Dog Agility Trail",
   "Sports Hall - Badminton Court x2",
   "Kids' Play Room (Taska)",
   "Gymnasium",
   "Games Room",
   "Co-working Space and Reading Room",
   "Function Hall and Pre-function Area",
   "Cascading Water Feature",
   "Strolling Pathway",
   "Covered Walkway",
   "Pool Deck",
   "Pavilion",
   "Toilet and Changing Room",
   "Open Lawn",
   "Playground",
   "Flower Garden",
   "Lap Pool",
   "Family Pool",
   "Kids' Pool with Waterplay",
   "Jacuzzi",
   "Sky BBQ Deck",
   "EV Charging Stations",
   "Car Wash Area",
   "Guardhouse",
   "Management Office",
   "Parcel Collection Room",
   "Mail Room",
   "Surau",
   "Space for Kindergarten",
   "Space for Laundry"
  ],
  "nearby": [
   {
    "category": "Highways & Expressways",
    "name": "Bukit Jalil Highway"
   },
   {
    "category": "Highways & Expressways",
    "name": "Kesas Expressway"
   },
   {
    "category": "Highways & Expressways",
    "name": "Kuala Lumpur - Seremban Expressway"
   },
   {
    "category": "Highways & Expressways",
    "name": "MEX Expressway"
   },
   {
    "category": "Highways & Expressways",
    "name": "LDP Expressway"
   },
   {
    "category": "Highways & Expressways",
    "name": "NPE Expressway"
   },
   {
    "category": "LRT Station",
    "name": "Alam Sutera Station",
    "distance": "1.5km"
   },
   {
    "category": "LRT Station",
    "name": "Kinrara BK5 Station",
    "distance": "2.5km"
   },
   {
    "category": "Shopping",
    "name": "Giant Kinrara",
    "distance": "2.5km"
   },
   {
    "category": "Shopping",
    "name": "Pavilion Bukit Jalil",
    "distance": "3.5km"
   },
   {
    "category": "Shopping",
    "name": "IOI Mall Puchong",
    "distance": "6.3km"
   },
   {
    "category": "Shopping",
    "name": "Sunway Pyramid Mall",
    "distance": "7.5km"
   },
   {
    "category": "Shopping",
    "name": "Mid Valley Megamall",
    "distance": "8.9km"
   },
   {
    "category": "Education",
    "name": "Tzu Chi International School",
    "distance": "3.9km"
   },
   {
    "category": "Education",
    "name": "SJK (C) Lai Meng",
    "distance": "3.8km"
   },
   {
    "category": "Education",
    "name": "International Medical University (IMU)",
    "distance": "5.2km"
   },
   {
    "category": "Education",
    "name": "Taylor’s University",
    "distance": "8.4km"
   },
   {
    "category": "Education",
    "name": "Sunway University",
    "distance": "6.9km"
   },
   {
    "category": "Education",
    "name": "Asia Pacific University (APU)",
    "distance": "8.2km"
   },
   {
    "category": "Healthcare",
    "name": "KPJ Kinrara",
    "distance": "1.8km"
   },
   {
    "category": "Healthcare",
    "name": "IMU Healthcare",
    "distance": "5.2km"
   },
   {
    "category": "Healthcare",
    "name": "Sunway Medical Centre",
    "distance": "6km"
   },
   {
    "category": "Healthcare",
    "name": "Columbia Asia Hospital",
    "distance": "6.9km"
   },
   {
    "category": "Leisure",
    "name": "Wawasan Recreational Park",
    "distance": "5.3km"
   },
   {
    "category": "Leisure",
    "name": "Bukit Jalil Recreational Park",
    "distance": "4km"
   },
   {
    "category": "Leisure",
    "name": "Bukit Jalil Golf & Country Resort",
    "distance": "5km"
   },
   {
    "category": "Leisure",
    "name": "Bukit Jalil National Stadium",
    "distance": "6.9km"
   }
  ]
 },
 "bangsar-hill-park-tower-b-and-c": {
  "source": "Developer sales kit (2026-08-11)",
  "keyFeatures": [
   "Urban Resort Home",
   "The Meeting Point of Nature and Urban Living",
   "Resort-inspired lifestyle amenities",
   "Conveniently connected to Kuala Lumpur's city centre and beyond"
  ],
  "facilities": [
   "Swimming Pool",
   "Spa Pool",
   "Kids Pool",
   "Amphitheatre",
   "BBQ Area",
   "Kids World / Children's Playground",
   "Gym",
   "Sauna/Steam Room",
   "Multipurpose Hall",
   "Study Room",
   "Gourmet Kitchen",
   "Basketball Court",
   "Badminton Court",
   "Games/Club Room",
   "Pavilion",
   "Hammock Area",
   "Management Office",
   "Mini Market",
   "Laundry",
   "Cafe",
   "Yoga Room",
   "Class Room",
   "Rooftop Whirlpool",
   "Rooftop BBQ Area",
   "Rooftop Seating Area",
   "Rooftop Children Playground"
  ],
  "nearby": [
   {
    "category": "Public Transport",
    "name": "Bank Rakyat – Bangsar LRT Station"
   },
   {
    "category": "Public Transport",
    "name": "KL Sentral (Largest Transportation Hub)"
   },
   {
    "category": "Public Transport",
    "name": "Pusat Bandar Damansara MRT Station"
   },
   {
    "category": "Highway Access",
    "name": "Sprint Highway"
   },
   {
    "category": "Highway Access",
    "name": "Federal Highway"
   },
   {
    "category": "Highway Access",
    "name": "NPE Highway"
   },
   {
    "category": "Highway Access",
    "name": "Damansara Link"
   },
   {
    "category": "Shopping Mall",
    "name": "KL Gateway Mall"
   },
   {
    "category": "Shopping Mall",
    "name": "Mid Valley Megamall"
   },
   {
    "category": "Shopping Mall",
    "name": "The Garden Mall"
   },
   {
    "category": "Shopping Mall",
    "name": "Bangsar Village"
   },
   {
    "category": "Shopping Mall",
    "name": "Bangsar Shopping Centre"
   },
   {
    "category": "Healthcare",
    "name": "Pantai Hospital Kuala Lumpur"
   },
   {
    "category": "Healthcare",
    "name": "IBC Integrated Healthcare & Wellness"
   },
   {
    "category": "Healthcare",
    "name": "University Hospital"
   },
   {
    "category": "Education",
    "name": "Cempaka International Schools Damansara Heights"
   },
   {
    "category": "Education",
    "name": "The Alice Smith International School"
   },
   {
    "category": "Education",
    "name": "HELP University"
   },
   {
    "category": "Education",
    "name": "University of Malaya"
   }
  ]
 },
 "bangsar-hill-park-verdura-tower-d-and-e": {
  "source": "Developer sales kit (2026-08-11)",
  "keyFeatures": [
   "Urban Resort Home",
   "The Meeting Point of Nature and Urban Living",
   "Resort-inspired lifestyle amenities",
   "Conveniently connected to Kuala Lumpur's city centre and beyond"
  ],
  "facilities": [
   "Swimming Pool",
   "Spa Pool",
   "Kids Pool",
   "Amphitheatre",
   "BBQ Area",
   "Kids World / Children's Playground",
   "Gym",
   "Sauna/Steam Room",
   "Multipurpose Hall",
   "Study Room",
   "Gourmet Kitchen",
   "Basketball Court",
   "Badminton Court",
   "Games/Club Room",
   "Pavilion",
   "Hammock Area",
   "Management Office",
   "Mini Market",
   "Laundry",
   "Cafe",
   "Yoga Room",
   "Class Room",
   "Rooftop Whirlpool",
   "Rooftop BBQ Area",
   "Rooftop Seating Area",
   "Rooftop Children Playground"
  ],
  "nearby": [
   {
    "category": "Public Transport",
    "name": "Bank Rakyat – Bangsar LRT Station"
   },
   {
    "category": "Public Transport",
    "name": "KL Sentral (Largest Transportation Hub)"
   },
   {
    "category": "Public Transport",
    "name": "Pusat Bandar Damansara MRT Station"
   },
   {
    "category": "Highway Access",
    "name": "Sprint Highway"
   },
   {
    "category": "Highway Access",
    "name": "Federal Highway"
   },
   {
    "category": "Highway Access",
    "name": "NPE Highway"
   },
   {
    "category": "Highway Access",
    "name": "Damansara Link"
   },
   {
    "category": "Shopping Mall",
    "name": "KL Gateway Mall"
   },
   {
    "category": "Shopping Mall",
    "name": "Mid Valley Megamall"
   },
   {
    "category": "Shopping Mall",
    "name": "The Garden Mall"
   },
   {
    "category": "Shopping Mall",
    "name": "Bangsar Village"
   },
   {
    "category": "Shopping Mall",
    "name": "Bangsar Shopping Centre"
   },
   {
    "category": "Healthcare",
    "name": "Pantai Hospital Kuala Lumpur"
   },
   {
    "category": "Healthcare",
    "name": "IBC Integrated Healthcare & Wellness"
   },
   {
    "category": "Healthcare",
    "name": "University Hospital"
   },
   {
    "category": "Education",
    "name": "Cempaka International Schools Damansara Heights"
   },
   {
    "category": "Education",
    "name": "The Alice Smith International School"
   },
   {
    "category": "Education",
    "name": "HELP University"
   },
   {
    "category": "Education",
    "name": "University of Malaya"
   }
  ]
 },
 "clouthaus": {
  "source": "Developer sales kit (2026-08-22)",
  "keyFeatures": [
   "KL's Most Iconic Address",
   "Hotel Services by Paradox Hotel KLCC",
   "Timeless, Luxury Interior Design",
   "Elevated Facilities for the High Life",
   "Branded Fittings and Appliances.",
   "Set the starting price at MYR 1.5 million",
   "Refrain from mentioning Airbnb, short-term stays, or high rental returns"
  ],
  "facilities": [
   "Explorer Playland",
   "Toilet (Male & Female)",
   "Discovery Play Club",
   "Reading Lounge",
   "Family Lounge",
   "Sky Lounge",
   "Sky Bar",
   "Karaoke Lounge",
   "Gym & Reformer Studio",
   "Yoga / Pilates Studio",
   "Games & Dining Lounge",
   "Mahjong Room",
   "Golf Simulator Room",
   "Music Room",
   "Toilet",
   "Sauna & Steam Room (Male & Female)",
   "Trellis Lounge",
   "Sky Pool",
   "Sky Jacuzzi",
   "Floating Lounge",
   "Leisure Pool",
   "Sky BBQ",
   "Sky Dining 1",
   "Sky Dining 2",
   "Clout Bar",
   "Sky DJ Deck",
   "Pre-Function Deck"
  ],
  "nearby": [
   {
    "category": "Attractions & Landmarks",
    "name": "Saloma Link Bridge"
   },
   {
    "category": "Attractions & Landmarks",
    "name": "Kampung Baru KL"
   },
   {
    "category": "Attractions & Landmarks",
    "name": "National Art Gallery"
   },
   {
    "category": "Attractions & Landmarks",
    "name": "KL Tower"
   },
   {
    "category": "Attractions & Landmarks",
    "name": "Kuala Lumpur Convention Centre"
   },
   {
    "category": "Attractions & Landmarks",
    "name": "Changkat Bukit Bintang"
   },
   {
    "category": "Attractions & Landmarks",
    "name": "Alor Street"
   },
   {
    "category": "Attractions & Landmarks",
    "name": "Chinatown"
   },
   {
    "category": "Attractions & Landmarks",
    "name": "Merdeka Stadium"
   },
   {
    "category": "Shopping & Leisure",
    "name": "Quill City Mall"
   },
   {
    "category": "Shopping & Leisure",
    "name": "Avenue K"
   },
   {
    "category": "Shopping & Leisure",
    "name": "Intermark Mall"
   },
   {
    "category": "Shopping & Leisure",
    "name": "KLCC Twin Towers"
   },
   {
    "category": "Shopping & Leisure",
    "name": "The LINC KL"
   },
   {
    "category": "Shopping & Leisure",
    "name": "Pavilion KL"
   },
   {
    "category": "Shopping & Leisure",
    "name": "Merdeka 118"
   },
   {
    "category": "Shopping & Leisure",
    "name": "Plaza Low Yat"
   },
   {
    "category": "Shopping & Leisure",
    "name": "Sungei Wang Plaza"
   },
   {
    "category": "Shopping & Leisure",
    "name": "Lot 10"
   },
   {
    "category": "Shopping & Leisure",
    "name": "Fahrenheit88"
   },
   {
    "category": "Shopping & Leisure",
    "name": "The Starhill"
   },
   {
    "category": "Shopping & Leisure",
    "name": "Berjaya Times Square"
   },
   {
    "category": "Shopping & Leisure",
    "name": "The Exchange 106"
   },
   {
    "category": "Shopping & Leisure",
    "name": "TREC KL"
   },
   {
    "category": "Medical",
    "name": "Kuala Lumpur Hospital"
   },
   {
    "category": "Medical",
    "name": "Institut Jantung Negara"
   },
   {
    "category": "Medical",
    "name": "Gleneagles Hospital"
   },
   {
    "category": "Medical",
    "name": "HSC Healthcare"
   },
   {
    "category": "Medical",
    "name": "Prince Court Medical Centre"
   },
   {
    "category": "Medical",
    "name": "Tung Shin Hospital"
   }
  ]
 },
 "core-residence-trx": {
  "source": "Developer sales kit (2026-08-24)",
  "keyFeatures": [],
  "facilities": [
   "Function Hall",
   "Reading Room",
   "Indoor Playground",
   "Outdoor Lounge",
   "Recreational Park",
   "Childcare Centre",
   "Sky Pool",
   "Sky Gym",
   "Wading Pool",
   "Pool Deck",
   "Sky Bar"
  ],
  "nearby": [
   {
    "category": "Nearby",
    "name": "Public Transport: TRX MRT Interchange Station",
    "distance": "MRT Line 1 & 2"
   },
   {
    "category": "Nearby",
    "name": "Shopping: The Exchange Mall (in TRX)"
   },
   {
    "category": "Nearby",
    "name": "Shopping: Pavilion Kuala Lumpur",
    "distance": "800m"
   },
   {
    "category": "Nearby",
    "name": "Shopping: Starhill Gallery, Fahrenheit 88, Lot 10"
   },
   {
    "category": "Nearby",
    "name": "Shopping: IKEA Cheras"
   },
   {
    "category": "Nearby",
    "name": "Healthcare: Prince Court Medical Centre",
    "distance": "900m"
   },
   {
    "category": "Nearby",
    "name": "Healthcare: HSC Medical Centre"
   },
   {
    "category": "Nearby",
    "name": "Healthcare: Gleneagles Hospital"
   },
   {
    "category": "Nearby",
    "name": "Education: EtonHouse International School"
   },
   {
    "category": "Nearby",
    "name": "Education: The International School of Kuala Lumpur (ISKL)"
   },
   {
    "category": "Nearby",
    "name": "Recreation: Royal Selangor Golf Club",
    "distance": "850m"
   },
   {
    "category": "Nearby",
    "name": "Recreation: TRX Central Park (10 acres)"
   },
   {
    "category": "Nearby",
    "name": "Highways: Maju Expressway (MEX), SMART Tunnel, Jalan Tun Razak, Jalan Sultan Ismail"
   },
   {
    "category": "Nearby",
    "name": "Landmarks: The Exchange 106 tower, Petronas Twin Towers",
    "distance": "1.8km"
   }
  ]
 },
 "genstarz": {
  "source": "Developer sales kit (2026-08-20)",
  "keyFeatures": [
   "Freehold",
   "Low density with only 360 units",
   "Flexible walls for customisation",
   "Nearby MRT & KTM stations",
   "3km to Mid Valley City",
   "GreenRE (Silver) Certified"
  ],
  "facilities": [
   "Ground Floor",
   "items: ['Guard House'",
   "'Retail shop']",
   "Level 7A (Podium)",
   "items: ['Prayer Room (Surau)'",
   "'Laundry Room'",
   "'Management Office'",
   "'Outdoor Fitness'",
   "'Kids’ Playground'",
   "'Lounge'",
   "'Multipurpose Hall'",
   "'Little Forest with Hanging Chair'",
   "'Open Lawn'",
   "'Swimming Pool'",
   "'Pool Lounge'",
   "'Gym (above Pool Lounge)'",
   "\"Wading Pool (Kid's pool)\"",
   "'BBQ Area'",
   "'Sundeck Lounge'",
   "'Jacuzzi']",
   "Level 43A (Rooftop)",
   "items: ['Sky Lounge'",
   "'Chillax Corner'",
   "'Movie Corner'",
   "'Reading / Working Corner']"
  ],
  "nearby": [
   {
    "category": "Transportation",
    "name": "Petaling KTM Station"
   },
   {
    "category": "Transportation",
    "name": "Pantai Dalam KTM Station"
   },
   {
    "category": "Transportation",
    "name": "Proposed MRT 3 Station"
   },
   {
    "category": "Shopping & Retail",
    "name": "Mid Valley City",
    "distance": "3km"
   },
   {
    "category": "Shopping & Retail",
    "name": "The Scott Garden"
   },
   {
    "category": "Shopping & Retail",
    "name": "Pearl Shopping Gallery"
   },
   {
    "category": "Shopping & Retail",
    "name": "NSK Trade City"
   },
   {
    "category": "Education",
    "name": "SJK(C) Choong Wen"
   },
   {
    "category": "Healthcare",
    "name": "KMI Taman Desa Medical Centre"
   },
   {
    "category": "Highways",
    "name": "New Pantai Expressway (NPE)"
   },
   {
    "category": "Highways",
    "name": "Jalan Klang Lama"
   }
  ]
 },
 "luminar-residence-federal-avenue": {
  "source": "Developer sales kit (2026-09-01)",
  "keyFeatures": [],
  "facilities": [
   "Kindergarten",
   "Washroom",
   "Management Office",
   "Parcel Room",
   "Surau",
   "Jacuzzi",
   "Shallow Pool",
   "Swimming Pool",
   "Sunken Seating",
   "Kids Pool",
   "Shower Area",
   "Pool Deck",
   "Basketball Half-Court",
   "BBQ Area",
   "Pavilion",
   "Reflexology Path",
   "Herb Garden",
   "Social Corner / Seating",
   "Hammock Garden",
   "Lawn",
   "Chillax Garden",
   "Games Room",
   "Reading Room",
   "Washroom/Changing Room",
   "Multipurpose Hall",
   "Outdoor Multipurpose Hall",
   "Gymnasium",
   "Children Playground",
   "Outdoor Fitness Station",
   "Open Terrace",
   "Utility",
   "Lift Lobby",
   "Pantry",
   "Landscape Deck"
  ],
  "nearby": [
   {
    "category": "Shopping Malls",
    "name": "Subang Parade Shopping Centre",
    "distance": "4km"
   },
   {
    "category": "Shopping Malls",
    "name": "Empire Shopping Gallery",
    "distance": "4km"
   },
   {
    "category": "Shopping Malls",
    "name": "AEON Mall Shah Alam",
    "distance": "5km"
   },
   {
    "category": "Shopping Malls",
    "name": "Paradigm Mall",
    "distance": "6km"
   },
   {
    "category": "Shopping Malls",
    "name": "Sunway Pyramid",
    "distance": "7km"
   },
   {
    "category": "Shopping Malls",
    "name": "Mid Valley Megamall",
    "distance": "15km"
   },
   {
    "category": "Education",
    "name": "Sri KDU International School",
    "distance": "2km"
   },
   {
    "category": "Education",
    "name": "SJK (C) Lick Hung",
    "distance": "5km"
   },
   {
    "category": "Education",
    "name": "INTI International University & Colleges",
    "distance": "6km"
   },
   {
    "category": "Education",
    "name": "Sunway University",
    "distance": "7km"
   },
   {
    "category": "Education",
    "name": "Taylor's University Lakeside Campus",
    "distance": "10km"
   },
   {
    "category": "Healthcare",
    "name": "Subang Jaya Medical Centre",
    "distance": "5km"
   },
   {
    "category": "Healthcare",
    "name": "KPJ Selangor Specialist Hospital",
    "distance": "6km"
   },
   {
    "category": "Healthcare",
    "name": "Sunway Medical Centre",
    "distance": "8km"
   },
   {
    "category": "Transportation",
    "name": "Batu Tiga KTM Station",
    "distance": "2km"
   },
   {
    "category": "Transportation",
    "name": "Subang Jaya LRT Station",
    "distance": "5km"
   },
   {
    "category": "Transportation",
    "name": "Subang Skypark Terminal",
    "distance": "12km"
   },
   {
    "category": "Transportation",
    "name": "Kuala Lumpur International Airport (KLIA)",
    "distance": "43km"
   },
   {
    "category": "Connectivity",
    "name": "Federal Highway",
    "distance": "0km"
   }
  ]
 },
 "m-aspira": {
  "source": "Developer sales kit (2026-08-10)",
  "keyFeatures": [],
  "facilities": [
   "Ground Floor / Level 1",
   "items: ['Drop-off'",
   "'Entrance Lobby'",
   "'Parcel Room & Mail Room'",
   "'Lift Lobby'",
   "'Nursery'",
   "'Kindergarten'",
   "'Retail'",
   "'Management Office'",
   "'Surau'",
   "'Landscape Garden'",
   "'Entrance Statement']",
   "Level 13 (Facilities Podium)",
   "items: ['50m Lap Pool'",
   "'Children Pool / Water Play'",
   "'Jacuzzi'",
   "'Sun Deck'",
   "'Family Deck'",
   "'Floating Pavilion'",
   "'Gymnasium'",
   "'Multi-purpose Hall'",
   "'Indoor Badminton / Pickleball Courts'",
   "\"Children's Playground\"",
   "\"Children's Play Room\"",
   "'Games Room'",
   "'Hanging Viewing Deck'",
   "'Co-working Space'",
   "'Gourmet Kitchen'",
   "'Outdoor Lounge'",
   "'Outdoor Dining & BBQ'",
   "'Changing Room'",
   "'Viewing Deck'",
   "'Glamping Area'",
   "'Covered Walkway']",
   "Level 69 (Tower B)",
   "items: ['Sky Lounge']"
  ],
  "nearby": [
   {
    "category": "Highways",
    "name": "SALAK Highway",
    "distance": "2 km"
   },
   {
    "category": "Highways",
    "name": "Setiawangsa-Pantai Expressway (SPE)",
    "distance": "2 km"
   },
   {
    "category": "Highways",
    "name": "KL-Seremban Expressway",
    "distance": "3 km"
   },
   {
    "category": "Highways",
    "name": "Federal Highway",
    "distance": "4.2 km"
   },
   {
    "category": "Highways",
    "name": "New Pantai Expressway (NPE)"
   },
   {
    "category": "Highways",
    "name": "Maju Expressway",
    "distance": "MEX"
   },
   {
    "category": "Shopping Malls",
    "name": "Mid Valley Megamall",
    "distance": "4.5 km"
   },
   {
    "category": "Shopping Malls",
    "name": "KL Gateway Mall",
    "distance": "5 km"
   },
   {
    "category": "Shopping Malls",
    "name": "KL Eco City",
    "distance": "5.3 km"
   },
   {
    "category": "Shopping Malls",
    "name": "NSK Trade City",
    "distance": "5.4 km"
   },
   {
    "category": "Shopping Malls",
    "name": "Pavilion Kuala Lumpur",
    "distance": "10.5 km"
   },
   {
    "category": "Shopping Malls",
    "name": "The Exchange TRX",
    "distance": "10.5 km"
   },
   {
    "category": "Shopping Malls",
    "name": "Sunway Velocity Mall"
   },
   {
    "category": "Shopping Malls",
    "name": "MyTOWN Shopping Centre"
   },
   {
    "category": "Shopping Malls",
    "name": "AEON Taman Maluri"
   },
   {
    "category": "Healthcare",
    "name": "KMI Taman Desa Medical Centre",
    "distance": "1.7 km"
   },
   {
    "category": "Healthcare",
    "name": "University Malaya Medical Centre",
    "distance": "5.9 km"
   },
   {
    "category": "Healthcare",
    "name": "Pantai Hospital Kuala Lumpur",
    "distance": "6.4 km"
   },
   {
    "category": "Healthcare",
    "name": "Tung Shin Hospital"
   },
   {
    "category": "Healthcare",
    "name": "Prince Court Medical Centre"
   },
   {
    "category": "Healthcare",
    "name": "Sunway Medical Centre Velocity"
   },
   {
    "category": "Education",
    "name": "SK Taman Desa",
    "distance": "2.1 km"
   },
   {
    "category": "Education",
    "name": "SMK Taman Desa",
    "distance": "2.1 km"
   },
   {
    "category": "Education",
    "name": "SMK Desa Perdana",
    "distance": "2.1 km"
   },
   {
    "category": "Education",
    "name": "Alice Smith School - Primary Campus",
    "distance": "7 km"
   },
   {
    "category": "Education",
    "name": "University of Malaya",
    "distance": "7.7 km"
   },
   {
    "category": "Education",
    "name": "SJK(C) Kuen Cheng 2",
    "distance": "8.2 km"
   },
   {
    "category": "Education",
    "name": "SJK(C) Kuen Cheng 1",
    "distance": "8.8 km"
   },
   {
    "category": "Education",
    "name": "Rocklin International School",
    "distance": "9.2 km"
   },
   {
    "category": "Recreation",
    "name": "Taman Rimba Bukit Kerinchi",
    "distance": "6 km"
   }
  ]
 },
 "maple-residences": {
  "source": "Developer sales kit (2026-08-07)",
  "keyFeatures": [],
  "facilities": [
   "The Oasis Garden",
   "The Elevated Deck Garden"
  ],
  "nearby": [
   {
    "category": "Highways",
    "name": "KESAS Highway"
   },
   {
    "category": "Highways",
    "name": "MRR2"
   },
   {
    "category": "Highways",
    "name": "Maju Expressway",
    "distance": "MEX"
   },
   {
    "category": "Highways",
    "name": "Bukit Jalil Highway"
   },
   {
    "category": "Highways",
    "name": "KL-Seremban Highway"
   },
   {
    "category": "Highways",
    "name": "New Pantai Expressway (NPE)"
   },
   {
    "category": "Highways",
    "name": "LDP Expressway"
   },
   {
    "category": "Public Transport",
    "name": "Sri Petaling LRT Station",
    "distance": "2.1 km"
   },
   {
    "category": "Public Transport",
    "name": "Awan Besar LRT Station",
    "distance": "2.5 km"
   },
   {
    "category": "Public Transport",
    "name": "Bandar Tasik Selatan Integrated Terminal (TBS)",
    "distance": "5.3 km"
   },
   {
    "category": "Public Transport",
    "name": "Taman Naga Emas MRT Station"
   },
   {
    "category": "Shopping",
    "name": "Endah Parade"
   },
   {
    "category": "Shopping",
    "name": "Pavilion Bukit Jalil"
   },
   {
    "category": "Shopping",
    "name": "Pearl Shopping Gallery"
   },
   {
    "category": "Shopping",
    "name": "Parkson OUG"
   },
   {
    "category": "Shopping",
    "name": "Mid Valley Megamall / The Gardens Mall"
   },
   {
    "category": "Shopping",
    "name": "IOI Mall Puchong"
   },
   {
    "category": "Shopping",
    "name": "Sunway Pyramid"
   },
   {
    "category": "Education",
    "name": "SJK(C) Yoke Nam"
   },
   {
    "category": "Education",
    "name": "SJK(C) La Salle"
   },
   {
    "category": "Education",
    "name": "SK Seri Indah"
   },
   {
    "category": "Education",
    "name": "SJK(C) Lai Meng"
   },
   {
    "category": "Education",
    "name": "SJK(C) Yak Chee Puchong"
   },
   {
    "category": "Education",
    "name": "International Medical University",
    "distance": "IMU"
   },
   {
    "category": "Education",
    "name": "Asia Pacific University of Technology & Innovation (APU)"
   },
   {
    "category": "Education",
    "name": "Kingsgate International School"
   },
   {
    "category": "Healthcare",
    "name": "IMU Healthcare"
   },
   {
    "category": "Healthcare",
    "name": "IMU Medical Centre"
   },
   {
    "category": "Healthcare",
    "name": "Taman Desa Medical Centre"
   },
   {
    "category": "Healthcare",
    "name": "Sunway Medical Centre"
   }
  ]
 },
 "oaka-residences": {
  "source": "Developer sales kit (2026-08-02)",
  "keyFeatures": [],
  "facilities": [
   "Guard House",
   "Drop Off Area",
   "Concourse",
   "Tower A Lobby",
   "Tower B Lobby",
   "Nursery",
   "Surau",
   "Management Office",
   "Retail",
   "Laundrette",
   "Mail Room",
   "Parcel Room",
   "Food Delivery Area",
   "Toilet",
   "Car Wash Area",
   "EV Charging Bays",
   "Half Basketball Court",
   "Lawn",
   "Wading Pool",
   "Infinity Pool",
   "Whirlpool Tub",
   "Pool Deck",
   "Outdoor Shower",
   "Pool Pavilion",
   "Sauna (male & female)",
   "Changing Room (male & female)",
   "Kid's Studio",
   "Multipurpose Hall",
   "Kitchen",
   "Children Playground",
   "Gymnasium",
   "Yoga Room / Dance Studio",
   "Games Room",
   "Theatre Room",
   "Resident's Lounge",
   "Water Feature With Fountain",
   "Viewing Gazebo",
   "BBQ Deck",
   "Pavilion",
   "Hammock Lawn"
  ],
  "nearby": [
   {
    "category": "Nearby",
    "name": "Awan Besar LRT Station"
   },
   {
    "category": "Nearby",
    "name": "Bukit Jalil LRT Station"
   },
   {
    "category": "Nearby",
    "name": "Sri Petaling LRT Station"
   },
   {
    "category": "Nearby",
    "name": "Bukit Jalil Highway"
   },
   {
    "category": "Nearby",
    "name": "Maju Expressway",
    "distance": "MEX"
   },
   {
    "category": "Nearby",
    "name": "Shah Alam Expressway (KESAS)"
   },
   {
    "category": "Nearby",
    "name": "Middle Ring Road 2",
    "distance": "MRR2"
   },
   {
    "category": "Kuala Lumpur",
    "name": "Seremban Expressway"
   },
   {
    "category": "Nearby",
    "name": "SUKE Highway"
   },
   {
    "category": "Nearby",
    "name": "Pavilion Bukit Jalil"
   },
   {
    "category": "Nearby",
    "name": "Pearl Point Shopping Mall"
   },
   {
    "category": "Nearby",
    "name": "The Tropika, Bukit Jalil"
   },
   {
    "category": "Nearby",
    "name": "The Link 2, Bukit Jalil"
   },
   {
    "category": "Columbia Asia Hospital",
    "name": "Bukit Jalil"
   },
   {
    "category": "Nearby",
    "name": "SJKC Lai Ming"
   },
   {
    "category": "Nearby",
    "name": "SMK Bukit Jalil"
   },
   {
    "category": "Nearby",
    "name": "Tzu Chi International School"
   },
   {
    "category": "Nearby",
    "name": "Kingsgate International School"
   },
   {
    "category": "Nearby",
    "name": "Sekolah Sukan Bukit Jalil"
   },
   {
    "category": "Nearby",
    "name": "Institut Sukan Negara"
   },
   {
    "category": "Nearby",
    "name": "International Medical University",
    "distance": "IMU"
   },
   {
    "category": "Nearby",
    "name": "Asia Pacific Institute of Information Technology (APIIT)"
   },
   {
    "category": "Nearby",
    "name": "Asia Pacific University of Technology & Innovation (APU)"
   },
   {
    "category": "Nearby",
    "name": "Bukit Jalil Recreational Park (80 acres)"
   },
   {
    "category": "Nearby",
    "name": "Bukit Jalil Golf & Country Resort"
   },
   {
    "category": "Nearby",
    "name": "Calvary Convention Centre"
   },
   {
    "category": "Nearby",
    "name": "Bukit Jalil National Stadium"
   },
   {
    "category": "Nearby",
    "name": "KL Sports City"
   }
  ]
 },
 "orion-residence": {
  "source": "Developer sales kit (2026-08-12)",
  "keyFeatures": [
   "Situated in the Bukit Bintang golden address",
   "Features a unique Limelight Façade with a moiré effect",
   "Offers an automated concierge parking system",
   "Includes a private security vault service managed by a Swiss security firm",
   "Branded residence with 5-star hospitality services",
   "Dual key units available for flexible living arrangements",
   "Fully furnished with high-end designer brands like Gaggenau, Miele, Bosch, and Kohler",
   "Rooftop facilities include a Sky Lounge, Moon Bar, and fine dining with panoramic city views."
  ],
  "facilities": [
   "The Galactic",
   "The Aquarius",
   "The Cosmos",
   "The Aurora",
   "The Constellation"
  ],
  "nearby": [
   {
    "category": "Shopping Mall",
    "name": "Starhill Gallery"
   },
   {
    "category": "Shopping Mall",
    "name": "Pavilion Kuala Lumpur"
   },
   {
    "category": "Shopping Mall",
    "name": "Lot 10"
   },
   {
    "category": "Shopping Mall",
    "name": "Suria KLCC",
    "distance": "2.9km"
   },
   {
    "category": "Public Transport",
    "name": "Bukit Bintang MRT/Monorail"
   },
   {
    "category": "Landmark",
    "name": "Tun Razak Exchange (TRX)"
   },
   {
    "category": "Landmark",
    "name": "KL Tower",
    "distance": "2.4km"
   },
   {
    "category": "Landmark",
    "name": "Merdeka PNB 118",
    "distance": "3.9km"
   },
   {
    "category": "Medical Centre",
    "name": "Prince Court Medical Centre",
    "distance": "1.2km"
   },
   {
    "category": "Medical Centre",
    "name": "Gleneagles Hospital",
    "distance": "4.7km"
   },
   {
    "category": "Medical Centre",
    "name": "Hospital Kuala Lumpur",
    "distance": "4.9km"
   },
   {
    "category": "Education",
    "name": "Taylor's International School",
    "distance": "3.4km"
   },
   {
    "category": "Education",
    "name": "Fairview International School",
    "distance": "4.5km"
   },
   {
    "category": "Education",
    "name": "Sayfol International School",
    "distance": "4.0km"
   },
   {
    "category": "Education",
    "name": "International School of Kuala Lumpur",
    "distance": "5.0km"
   },
   {
    "category": "Recreation",
    "name": "Royal Selangor Golf Club",
    "distance": "4.0km"
   }
  ]
 },
 "park-green-pavilion-bukit-jalil": {
  "source": "Developer sales kit (2026-08-05)",
  "keyFeatures": [],
  "facilities": [
   "3: Dedicated pedestrian bridge to Pavilion Bukit Jalil",
   "Visitor Car Park",
   "OKU Parking (15 lots)",
   "Swimming Pool (Approx. 30m x 10m x 1.2m)",
   "Shop",
   "Multi-Purpose Hall (MPH)",
   "Games Room",
   "Coworking Lounge 1",
   "Coworking Lounge 2",
   "Sky Terrace",
   "Sky Lounge",
   "Gymnasium",
   "Yoga Area",
   "Concierge Service",
   "Residents' Car Park (Level B1",
   "1M to 10A)",
   "Motorcycle Bays (Level B1",
   "2 to 10A)",
   "Loading and Unloading Area (Level B2)"
  ],
  "nearby": [
   {
    "category": "Shopping Mall",
    "name": "Pavilion Bukit Jalil"
   }
  ]
 },
 "quaver-residence": {
  "source": "Developer sales kit (2026-08-07)",
  "keyFeatures": [],
  "facilities": [
   "Level 11",
   "list: ['Swimming Pool'",
   "'Wading Pool & Water Play'",
   "'Pool Deck'",
   "'Jacuzzi'",
   "'Gymnasium'",
   "'Games Room'",
   "'Lounge'",
   "'Reading Room'",
   "'Playground'",
   "'Multipurpose Hall / Badminton Hall'",
   "'Function Room'",
   "'Yoga Deck'",
   "'Open Space for Dining'",
   "'Garden Fitness'",
   "'Sensory Garden'",
   "'Co-working Lounge'",
   "'Chirping Park'",
   "'Surau'",
   "'Changing Room']",
   "Rooftop",
   "Other",
   "list: ['Visitor Carpark']"
  ],
  "nearby": [
   {
    "category": "Highways & Expressways",
    "name": "Kuala Lumpur - Seremban Expressway"
   },
   {
    "category": "Highways & Expressways",
    "name": "Sungai Besi Expressway (BESRAYA)"
   },
   {
    "category": "Highways & Expressways",
    "name": "Bukit Jalil Highway"
   },
   {
    "category": "Highways & Expressways",
    "name": "Kesas Expressway"
   },
   {
    "category": "Highways & Expressways",
    "name": "SUKE Expressway"
   },
   {
    "category": "Public Transport",
    "name": "MRT Serdang Raya Utara Station",
    "distance": "700m away, via pedestrian link"
   },
   {
    "category": "Shopping & Retail",
    "name": "The Mines Shopping Mall",
    "distance": "3.4km"
   },
   {
    "category": "Shopping & Retail",
    "name": "Pavilion Bukit Jalil",
    "distance": "4km"
   },
   {
    "category": "Shopping & Retail",
    "name": "Giant Kinrara",
    "distance": "9.7km"
   },
   {
    "category": "Education",
    "name": "Asia Pacific University (APU)",
    "distance": "3.1km"
   },
   {
    "category": "Education",
    "name": "Technology Park Malaysia",
    "distance": "3.3km"
   },
   {
    "category": "Education",
    "name": "International Medical University (IMU)",
    "distance": "5km"
   },
   {
    "category": "Healthcare",
    "name": "IMU Hospital",
    "distance": "5km"
   },
   {
    "category": "Healthcare",
    "name": "Columbia Asia Hospital Cheras",
    "distance": "9km"
   }
  ]
 },
 "tria-seputeh": {
  "source": "Developer sales kit (2026-08-18)",
  "keyFeatures": [
   "Exclusivity: Low density (as low as 7 units per floor), private clubhouse, up to 6 carparks per unit",
   "Privacy: Purely residential title, individual tower drop-off lobbies, enhanced corridor design",
   "Green: Over 52 facilities across 3 acres of green space, including a riverside Promenade Boulevard, treehouses, and water brooks",
   "Security: Gated & guarded with 3-tier security, perimeter electrical fencing, and anti-climb fence."
  ],
  "facilities": [
   "Greeting Cards",
   "Evergreen Garden",
   "Pathway Garden",
   "Water Cantata",
   "Grasscrete Access",
   "The Flow",
   "River Walk",
   "Multi Layer Park",
   "Drop Off Lobby Gardens",
   "Badminton and Basketball Court",
   "50m Infinity Pool",
   "Wading Pool",
   "Aqua Gym",
   "Jacuzzi",
   "Chess Garden",
   "BBQ Deck",
   "Camping Site",
   "Skate Park",
   "Callisthenic Play",
   "Breeze Tree House",
   "Water Tree House",
   "Rock Climbing",
   "Water Brooks",
   "Pavillion",
   "River View Gymnasium",
   "Function Room",
   "Sunken Deck / Meditation Garden",
   "Private Clubhouse (Private Lounge",
   "Teen's Club",
   "Kids' Edu Hub)",
   "BBQ Area",
   "Pavilion",
   "Seating Alcoves",
   "Reading Pod",
   "Hammock Garden",
   "Sunken Lounge",
   "Maze Garden",
   "Herbs Garden",
   "Light Pavilion",
   "Parcourse Walk & Four Season Garden"
  ],
  "nearby": [
   {
    "category": "Highways",
    "name": "New Pantai Expressway (NPE)"
   },
   {
    "category": "Highways",
    "name": "Federal Highway"
   },
   {
    "category": "Highways",
    "name": "Kesas Highway"
   },
   {
    "category": "Highways",
    "name": "Dedicated OKR-NPE Link Bridge"
   },
   {
    "category": "Shopping Malls",
    "name": "Mid Valley Megamall",
    "distance": "1km"
   },
   {
    "category": "Shopping Malls",
    "name": "The Gardens Mall"
   },
   {
    "category": "Shopping Malls",
    "name": "KL Gateway Mall",
    "distance": "2km"
   },
   {
    "category": "Shopping Malls",
    "name": "Nu Sentral Mall"
   },
   {
    "category": "Shopping Malls",
    "name": "Bangsar Shopping Centre"
   },
   {
    "category": "Shopping Malls",
    "name": "Pavilion Kuala Lumpur"
   },
   {
    "category": "Shopping Malls",
    "name": "Suria KLCC",
    "distance": "5km"
   },
   {
    "category": "Transportation Hubs",
    "name": "KL Sentral"
   },
   {
    "category": "Transportation Hubs",
    "name": "Bandar Malaysia (future)"
   },
   {
    "category": "Education",
    "name": "Campus Rangers International School"
   },
   {
    "category": "Education",
    "name": "HELP University"
   },
   {
    "category": "Education",
    "name": "University of Malaya"
   },
   {
    "category": "Education",
    "name": "Alice Smith School"
   },
   {
    "category": "Education",
    "name": "Gardens International School"
   },
   {
    "category": "Healthcare",
    "name": "Taman Desa Medical Centre"
   },
   {
    "category": "Healthcare",
    "name": "Pantai Hospital Kuala Lumpur"
   },
   {
    "category": "Healthcare",
    "name": "University Malaya Medical Centre"
   },
   {
    "category": "Healthcare",
    "name": "Prince Court Medical Centre"
   },
   {
    "category": "Healthcare",
    "name": "Gleneagles Kuala Lumpur"
   },
   {
    "category": "Business & Commercial Hubs",
    "name": "Mid Valley City",
    "distance": "1km"
   },
   {
    "category": "Business & Commercial Hubs",
    "name": "KL Eco City",
    "distance": "1km"
   },
   {
    "category": "Business & Commercial Hubs",
    "name": "Bangsar South",
    "distance": "2km"
   },
   {
    "category": "Business & Commercial Hubs",
    "name": "KL Sentral"
   }
  ]
 },
 "tujuh-residences": {
  "source": "Developer sales kit (2026-09-09)",
  "keyFeatures": [],
  "facilities": [
   "The Entrance (Guard House)",
   "Convenience Store",
   "Laundry",
   "Cafe",
   "Kindergarten",
   "Play Area",
   "Praying Hall (Surau)",
   "Indoor Play Area",
   "Games Room",
   "Reading Room",
   "Management Office",
   "Mailbox",
   "Waiting Lounge",
   "Entrance Drop-off",
   "Visitor Car Parks with EV Chargers (3 nos.)",
   "Car Wash Bay",
   "Swimming Pool",
   "Wading Pool",
   "BBQ Pit / Chill Out Area",
   "Water Fun Zone",
   "Outdoor Shower Area",
   "Multipurpose Open Lawn",
   "Seating Wall",
   "Gazebo",
   "Pool Lounge Chair",
   "Garden Step",
   "Yoga Deck",
   "Gym",
   "Multipurpose Hall"
  ],
  "nearby": [
   {
    "category": "Highways",
    "name": "DASH Highway",
    "distance": "1km"
   },
   {
    "category": "Highways",
    "name": "Guthrie Corridor Expressway",
    "distance": "4.5km"
   },
   {
    "category": "Highways",
    "name": "North Klang Valley Expressway (NKVE)",
    "distance": "4km"
   },
   {
    "category": "Highways",
    "name": "North-South Expressway",
    "distance": "6km"
   },
   {
    "category": "Public Transport",
    "name": "Kwasa Sentral MRT Station",
    "distance": "MRT Kajang Line"
   },
   {
    "category": "Public Transport",
    "name": "Subang Skypark KTM Station",
    "distance": "5km"
   },
   {
    "category": "Shopping Malls",
    "name": "Star Avenue Lifestyle Mall",
    "distance": "4.5km"
   },
   {
    "category": "Shopping Malls",
    "name": "Tropicana Gardens Mall",
    "distance": "5.6km"
   },
   {
    "category": "Shopping Malls",
    "name": "Sunway Giza Mall"
   },
   {
    "category": "Shopping Malls",
    "name": "The Curve"
   },
   {
    "category": "Shopping Malls",
    "name": "1 Utama Shopping Centre",
    "distance": "11.1km"
   },
   {
    "category": "Education",
    "name": "SMK Seksyen 10 Kota Damansara",
    "distance": "1.4km"
   },
   {
    "category": "Education",
    "name": "HELP International School / HELP University",
    "distance": "2.3km"
   },
   {
    "category": "Education",
    "name": "Sri KDU School",
    "distance": "2.6km"
   },
   {
    "category": "Education",
    "name": "SEGi University"
   },
   {
    "category": "Education",
    "name": "IGB International School",
    "distance": "6.4km"
   },
   {
    "category": "Education",
    "name": "SJK (C) Damansara",
    "distance": "6.9km"
   },
   {
    "category": "Education",
    "name": "Asia Pacific Schools"
   },
   {
    "category": "Hospitals",
    "name": "Thomson Hospital Kota Damansara",
    "distance": "5.8km"
   },
   {
    "category": "Hospitals",
    "name": "Sungai Buloh Hospital",
    "distance": "7km"
   },
   {
    "category": "Recreation",
    "name": "Kota Damansara Community Forest Reserve"
   },
   {
    "category": "Recreation",
    "name": "Tropicana Golf & Country Resort"
   },
   {
    "category": "Airport",
    "name": "Sultan Abdul Aziz Shah Airport (Subang Airport)",
    "distance": "5km"
   }
  ]
 },
 "zenia-damansara": {
  "source": "Developer sales kit (2026-08-27)",
  "keyFeatures": [],
  "facilities": [
   "Level G",
   "items: ['Main Pool'",
   "'Pool Deck'",
   "\"Kid's Pool\"",
   "'Reading & Work Loft'",
   "'Changing Room'",
   "'BBQ Pavilion'",
   "'Multipurpose Hall'",
   "'Seating Terrace'",
   "'Multi Court'",
   "'Family Pool'",
   "'Prayer Room'",
   "'Kindergarten'",
   "'Playground'",
   "'Outdoor Fitness'",
   "'Reflexology Path'",
   "'Connecting Access']",
   "Level LG1",
   "items: ['Guardhouse'",
   "'Arrival Plaza'",
   "'Utility/Locker'",
   "'Games Room'",
   "'Music Room'",
   "'Kids Playroom'",
   "'Makers Studio'",
   "'Study'",
   "'Lounge'",
   "'Management Office'",
   "'Convenience Store'",
   "'Outdoor Deck'",
   "'Outdoor Deck Seating Lounge'",
   "'Lobby'",
   "'Drop-off']",
   "Level LG2",
   "items: ['Utility/Locker'",
   "'Entertainment Room'",
   "'Refuse Chamber'",
   "'Lobby']",
   "Level LG3",
   "'Gym'"
  ],
  "nearby": [
   {
    "category": "Highways",
    "name": "North-South Expressway"
   },
   {
    "category": "Highways",
    "name": "Damansara-Puchong Expressway (LDP)"
   },
   {
    "category": "Highways",
    "name": "DASH Highway"
   },
   {
    "category": "Highways",
    "name": "Penchala Link"
   },
   {
    "category": "Highways",
    "name": "SPRINT Expressway"
   },
   {
    "category": "Highways",
    "name": "New Klang Valley Expressway (NKVE)"
   },
   {
    "category": "Public Transport",
    "name": "Kwasa Sentral MRT Station"
   },
   {
    "category": "Public Transport",
    "name": "Surian MRT Station"
   },
   {
    "category": "Public Transport",
    "name": "Mutiara Damansara MRT Station"
   },
   {
    "category": "Public Transport",
    "name": "Bandar Utama MRT Station"
   },
   {
    "category": "Shopping Malls",
    "name": "The Curve"
   },
   {
    "category": "Shopping Malls",
    "name": "IPC Shopping Centre"
   },
   {
    "category": "Shopping Malls",
    "name": "1 Utama Shopping Centre"
   },
   {
    "category": "Shopping Malls",
    "name": "Sunway GIZA Mall"
   },
   {
    "category": "Shopping Malls",
    "name": "IOI Mall Damansara"
   },
   {
    "category": "Hospitals",
    "name": "Thomson Hospital Kota Damansara"
   },
   {
    "category": "Hospitals",
    "name": "Sunway Specialist Centre Damansara"
   },
   {
    "category": "Hospitals",
    "name": "Damansara Specialist Hospital"
   },
   {
    "category": "Education",
    "name": "HELP University"
   },
   {
    "category": "Education",
    "name": "SEGI University"
   },
   {
    "category": "Education",
    "name": "SJK(C) Damansara"
   },
   {
    "category": "Education",
    "name": "Asia Pacific Schools"
   },
   {
    "category": "Recreation",
    "name": "Tropicana Golf & Country Resort"
   },
   {
    "category": "Recreation",
    "name": "Seri Selangor Golf Club"
   },
   {
    "category": "Recreation",
    "name": "Kuala Lumpur Golf & Country Club (KLGCC)"
   },
   {
    "category": "Recreation",
    "name": "The Club @ Bukit Utama"
   },
   {
    "category": "Recreation",
    "name": "Bukit Kiara Park"
   },
   {
    "category": "Other Landmarks",
    "name": "Menara KWSP"
   },
   {
    "category": "Other Landmarks",
    "name": "Subang Airport"
   }
  ]
 },
 "ren-residence": {
  "source": "Developer sales kit (2026-08-04)",
  "keyFeatures": [
   "Designed in a unique '人' shape for optimum sunlight and views",
   "Up to 4+1 bedrooms & 3 bathrooms",
   "Over an acre of family-friendly recreational facilities",
   "3-tier security with face recognition and license plate recognition access",
   "2 to 3 parking bays per unit",
   "Co-working spaces available",
   "Each tower served by 5+1 lifts."
  ],
  "facilities": [
   "Infinity Swimming Pool",
   "Pool Deck",
   "Quiet Pool",
   "Jacuzzi - 1",
   "Jacuzzi - 2",
   "Shallow Pool",
   "Pool Terrace",
   "Kid Slider Pool",
   "Kid Pool",
   "Kid Play Pool",
   "Kid Shallow Pool",
   "Kid Small Pool",
   "Parent Seating Area",
   "Outdoor Shower",
   "Artificial Turf",
   "Multipurpose Artificial Turf",
   "Plaza",
   "Outdoor Meeting-1",
   "Outdoor Meeting-2",
   "Outdoor Lounge",
   "Picnic Court",
   "BBQ Area",
   "Children Play Station",
   "Children Twin Swing",
   "Children Mini Climb Wall",
   "Children Berm Play",
   "Children Sand Pit",
   "Children Balancing",
   "Outdoor Gym Station",
   "Pocket Garden",
   "Jogging Track",
   "Yoga Deck",
   "Children Play Net-1",
   "Children Play Net-2",
   "Stone Foot Therapy",
   "Basketball Court",
   "Tennis / Futsal Court",
   "Seating Area",
   "Changing Room-1",
   "Changing Room-2"
  ],
  "nearby": [
   {
    "category": "Highways",
    "name": "KESAS Highway"
   },
   {
    "category": "Highways",
    "name": "Bukit Jalil Highway"
   },
   {
    "category": "Highways",
    "name": "KL-Seremban Expressway"
   },
   {
    "category": "Highways",
    "name": "Sungai Besi Expressway"
   },
   {
    "category": "Public Transport",
    "name": "Alam Sutera LRT Station"
   },
   {
    "category": "Shopping & Retail",
    "name": "Pavilion Bukit Jalil"
   },
   {
    "category": "Shopping & Retail",
    "name": "Giant Hypermarket Bandar Kinrara"
   },
   {
    "category": "Education",
    "name": "Tzu Chi International School"
   },
   {
    "category": "Education",
    "name": "International Medical University",
    "distance": "IMU"
   },
   {
    "category": "Education",
    "name": "Kingsgate International School"
   },
   {
    "category": "Education",
    "name": "Technology Park Malaysia"
   },
   {
    "category": "Recreation",
    "name": "Bukit Jalil Golf & Country Club"
   },
   {
    "category": "Recreation",
    "name": "Kinrara Golf Club"
   },
   {
    "category": "Recreation",
    "name": "Pavillion Recreational Park"
   },
   {
    "category": "Recreation",
    "name": "National Stadium Bukit Jalil"
   }
  ]
 },
 "aras-residence": {
  "source": "Developer sales kit (2026-08-07)",
  "keyFeatures": [
   "Freehold Parkfront Living",
   "One of the tallest buildings in the vicinity",
   "3.1m clear ceiling height",
   "North-South orientation with KL City or Bukit Jalil views",
   "Over 50 exclusive facilities across Ground, Level 9, and Level 56 Sky Terrace",
   "Multi-tier security system",
   "50m Olympic-length lap pool",
   "EV charging bays",
   "Automated waste collection system",
   "Destination lift control system."
  ],
  "facilities": [
   "Delivery waiting area",
   "Dedicated visitors lift",
   "Porte cochere",
   "Guard house",
   "Linear park (200m)",
   "Parcel area",
   "Mail room",
   "Main entrance lounge",
   "Residence lobby",
   "Nursery",
   "Kindergarten",
   "Management office",
   "50m Lap pool",
   "Hydrotherapy pool",
   "Aqua gym pool",
   "Lounge pool",
   "Onsen pool",
   "Kid's pool",
   "Feature cabana",
   "Gymnasium",
   "Multi-purpose hall",
   "Games room",
   "Table tennis room",
   "VR room",
   "Podcast Room",
   "Social kitchen",
   "Reading room",
   "Yoga room",
   "Sauna room",
   "Steam room",
   "Children's playground",
   "BBQ terrace & pavilion",
   "Tea Terrace",
   "Zen garden",
   "Sky Terrace / Viewing Deck"
  ],
  "nearby": [
   {
    "category": "Highways",
    "name": "KESAS Highway"
   },
   {
    "category": "Highways",
    "name": "Maju Expressway",
    "distance": "MEX"
   },
   {
    "category": "Highways",
    "name": "Bukit Jalil Highway"
   },
   {
    "category": "Highways",
    "name": "KL-Seremban Highway"
   },
   {
    "category": "Highways",
    "name": "NPE Highway"
   },
   {
    "category": "Public Transport",
    "name": "Sri Petaling LRT Station"
   },
   {
    "category": "Public Transport",
    "name": "Bukit Jalil LRT Station"
   },
   {
    "category": "Public Transport",
    "name": "Awan Besar LRT Station"
   },
   {
    "category": "Public Transport",
    "name": "Muhibbah LRT Station"
   },
   {
    "category": "Public Transport",
    "name": "Taman Naga Emas MRT Station"
   },
   {
    "category": "Shopping",
    "name": "Endah Parade"
   },
   {
    "category": "Shopping",
    "name": "Pearl Shopping Gallery"
   },
   {
    "category": "Shopping",
    "name": "Pavilion Bukit Jalil"
   },
   {
    "category": "Shopping",
    "name": "Midvalley Megamall & The Gardens Mall"
   },
   {
    "category": "Education",
    "name": "SK Seri Indah"
   },
   {
    "category": "Education",
    "name": "International Medical University",
    "distance": "IMU"
   },
   {
    "category": "Education",
    "name": "SJK(C) Lai Meng"
   },
   {
    "category": "Education",
    "name": "Asia Pacific University (APU)"
   },
   {
    "category": "Healthcare",
    "name": "IMU Healthcare"
   },
   {
    "category": "Healthcare",
    "name": "Columbia Asia Hospital Bukit Jalil"
   },
   {
    "category": "Healthcare",
    "name": "Taman Desa Medical Centre"
   },
   {
    "category": "Recreation",
    "name": "Bukit Jalil National Stadium"
   },
   {
    "category": "Recreation",
    "name": "Bukit Jalil Recreational Park"
   },
   {
    "category": "Recreation",
    "name": "Bukit Jalil Golf & Country Resort"
   }
  ]
 },
 "vividz": {
  "source": "Developer sales kit (2026-08-04)",
  "keyFeatures": [],
  "facilities": [
   "Physiotherapy Room",
   "Lobby Lounge A",
   "Grand Entrance",
   "Vividz Walk",
   "Drop-off",
   "Lobby Lounge B",
   "Yoga Studio",
   "Body Builder Studio",
   "Gourmet Villa",
   "Leisure Villa",
   "Social Lounge A",
   "Social Lounge B",
   "Topaz Jacuzzi",
   "Topaz Kid's Pool",
   "Tanning Bed",
   "Vividz Pool",
   "Blush Swing",
   "Butterscotch Garden",
   "Amphitheater",
   "Golden Years Gym",
   "Chromatic Funland",
   "Multipurpose Hall (Pickle Ball & Badminton Court)",
   "Grill Garden",
   "Serene Pavilion",
   "Herbs Garden",
   "Cloud Lounge"
  ],
  "nearby": [
   {
    "category": "Public Transport",
    "name": "Rapid KL Bus Stop (KL2016 Taman LTAT, Route T581)",
    "distance": "0.5km"
   },
   {
    "category": "Public Transport",
    "name": "LRT Alam Sutera (SP21)",
    "distance": "2km"
   },
   {
    "category": "Public Transport",
    "name": "Proposed Shuttle Bus Service to Pavilion Bukit Jalil & Awan Besar LRT"
   },
   {
    "category": "Highways",
    "name": "KESAS Highway"
   },
   {
    "category": "Highways",
    "name": "Maju Expressway",
    "distance": "MEX"
   },
   {
    "category": "Highways",
    "name": "Damansara-Puchong Expressway (LDP)"
   },
   {
    "category": "Highways",
    "name": "NPE: Kuchai Link"
   },
   {
    "category": "Highways",
    "name": "Sungai Besi Expressway (BESRAYA)"
   },
   {
    "category": "Shopping Malls",
    "name": "Pavilion Bukit Jalil",
    "distance": "1.4km"
   },
   {
    "category": "Shopping Malls",
    "name": "Aurora Place Bukit Jalil",
    "distance": "2.1km"
   },
   {
    "category": "Shopping Malls",
    "name": "Giant Hypermarket @ Bukit Kinrara",
    "distance": "5km"
   },
   {
    "category": "Shopping Malls",
    "name": "IOI Puchong Mall",
    "distance": "8.5km"
   },
   {
    "category": "Shopping Malls",
    "name": "Mid Valley Megamall",
    "distance": "11.5km"
   },
   {
    "category": "Hospitals & Medical Centres",
    "name": "KL Wellness City",
    "distance": "0km"
   },
   {
    "category": "Hospitals & Medical Centres",
    "name": "KMI Taman Desa Medical Centre",
    "distance": "8.1km"
   },
   {
    "category": "Hospitals & Medical Centres",
    "name": "Sunway Medical Centre",
    "distance": "8.4km"
   },
   {
    "category": "Hospitals & Medical Centres",
    "name": "Columbia Asia Hospital Puchong",
    "distance": "9.8km"
   },
   {
    "category": "Education",
    "name": "Tzu Chi International School Kuala Lumpur",
    "distance": "1.4km"
   },
   {
    "category": "Education",
    "name": "SJK (C) Lai Meng",
    "distance": "3.2km"
   },
   {
    "category": "Education",
    "name": "SMK Seksyen 1 Bandar Kinrara",
    "distance": "3.3km"
   },
   {
    "category": "Education",
    "name": "International Medical University (IMU)",
    "distance": "5km"
   },
   {
    "category": "Education",
    "name": "Sunway University",
    "distance": "9.2km"
   },
   {
    "category": "Recreation",
    "name": "Bukit Jalil Recreational Park"
   },
   {
    "category": "Recreation",
    "name": "Bukit Jalil Golf & Country Club"
   }
  ]
 },
 "khaya-residence": {
  "source": "Developer sales kit (2026-08-10)",
  "keyFeatures": [
   "Bangsar – The Pinnacle of Affluent Living",
   "Iconic Façade Design",
   "Unrivalled Views from Every Angle",
   "Prime Central Location between KL and PJ",
   "Seamless Accessibility via major expressways",
   "Unmatched Connectivity with a 5-min walk to LRT",
   "Surrounded by Established Amenities",
   "Over 40 lifestyle-facilities."
  ],
  "facilities": [
   "Pickleball Court / Multipurpose Hall",
   "Changing Rooms (South & North)",
   "Surau",
   "Reading Room",
   "Laundromat",
   "Management Office",
   "Music Room",
   "Home Theatre",
   "Private Party Room",
   "Game Room",
   "Lounge & Co-Working Space",
   "Children's Playroom",
   "Yoga / Dance Room",
   "Sauna Room",
   "Bar Counter & Pantry",
   "Dining Lounge",
   "Twilight Garden",
   "50m Lap Pool",
   "Sunbath Lounge",
   "Hammock Garden",
   "Wading Pool",
   "Fiddlehead Waterplay",
   "Adventure Playtower",
   "Putting Green",
   "Grove Walk",
   "Cabanas (Root, Steam, The Leaf)",
   "Green Boulevard",
   "Party Lawn",
   "Picnic Garden",
   "Eco Pond",
   "Dining Pavilion 'Monstera' (BBQ, Jacuzzi, Shower)",
   "Dining Pavilion 'Philodendron' (BBQ, Jacuzzi, Shower)",
   "Herb Garden",
   "Outdoor Fitness",
   "Sunken Lounge",
   "Reflexology Path",
   "Sensory Garden",
   "Outdoor Sport",
   "Multi-Purpose Room",
   "Sky Gym"
  ],
  "nearby": [
   {
    "category": "Highways",
    "name": "Federal Highway"
   },
   {
    "category": "Highways",
    "name": "New Pantai Expressway (NPE)"
   },
   {
    "category": "Highways",
    "name": "Sprint Expressway"
   },
   {
    "category": "Highways",
    "name": "Salak Expressway"
   },
   {
    "category": "Public Transport",
    "name": "LRT Abdullah Hukum",
    "distance": "5-minute walk"
   },
   {
    "category": "Public Transport",
    "name": "LRT Kerinchi"
   },
   {
    "category": "Public Transport",
    "name": "LRT Universiti"
   },
   {
    "category": "Public Transport",
    "name": "LRT Bangsar"
   },
   {
    "category": "Public Transport",
    "name": "MRT Pusat Bandar Damansara"
   },
   {
    "category": "Public Transport",
    "name": "KTM Angkasapuri"
   },
   {
    "category": "Public Transport",
    "name": "KTM Mid Valley"
   },
   {
    "category": "Shopping Malls",
    "name": "The Gardens Mall & Mid Valley Megamall"
   },
   {
    "category": "Shopping Malls",
    "name": "Bangsar Shopping Centre (BSC)"
   },
   {
    "category": "Shopping Malls",
    "name": "Bangsar Village I & II"
   },
   {
    "category": "Shopping Malls",
    "name": "Pavilion Mall, Damansara Heights"
   },
   {
    "category": "Shopping Malls",
    "name": "Nu Sentral Mall"
   },
   {
    "category": "Shopping Malls",
    "name": "KL Gateway Mall"
   },
   {
    "category": "Shopping Malls",
    "name": "Nexus Bangsar South"
   },
   {
    "category": "Shopping Malls",
    "name": "The Sphere"
   },
   {
    "category": "Shopping Malls",
    "name": "KL Eco City Mall"
   },
   {
    "category": "Healthcare",
    "name": "Pantai Hospital Kuala Lumpur"
   },
   {
    "category": "Healthcare",
    "name": "UM Specialist Centre",
    "distance": "UMSC"
   },
   {
    "category": "Healthcare",
    "name": "University of Malaya Medical Centre"
   },
   {
    "category": "Healthcare",
    "name": "Cardiac Vascular Sentral KL (CVSKL)"
   },
   {
    "category": "Healthcare",
    "name": "International Specialist Eye Centre (ISEC)"
   },
   {
    "category": "Healthcare",
    "name": "Life Care Diagnostic Medical Centre"
   },
   {
    "category": "Education",
    "name": "University of Malaya"
   },
   {
    "category": "Education",
    "name": "HELP University"
   },
   {
    "category": "Education",
    "name": "Alice Smith School"
   },
   {
    "category": "Education",
    "name": "Cempaka International School"
   }
  ]
 },
 "phoeniz-suites-kl-city-centre": {
  "source": "Developer sales kit (2026-08-30)",
  "keyFeatures": [
   "Excellent choice for investment in KL downtown",
   "Within CBD and Golden Triangle Area",
   "KLCC, Pavilion shopping mall within 5 min driving distance",
   "Walking distance to bus stop and MRT station",
   "Top-notch facilities for lifestyle & business",
   "Free upgrade to premier fully furnished by MMH",
   "Up to 90% loan margin for HDA units",
   "Proven developer track record",
   "GreenRE Bronze certified Green Building."
  ],
  "facilities": [
   "Lobby",
   "Mechanical Car Park",
   "OKU Car Park",
   "1: Parcel Room, Mailroom, Motorcycle Parking",
   "Concierge Lobby",
   "Reception Lobby",
   "Meeting Room",
   "Taska / Nursing Room",
   "Sky Gym",
   "Sky Music Lounge",
   "Water Tank & Pump Room",
   "Sky Pool",
   "Sky Pool Deck",
   "Garden Lounge",
   "24-hour Security with Access Card System",
   "CCTV",
   "Landscaping"
  ],
  "nearby": [
   {
    "category": "Transportation",
    "name": "AKLEH Highway"
   },
   {
    "category": "Transportation",
    "name": "Walking distance to bus stop and MRT station"
   },
   {
    "category": "Shopping",
    "name": "Suria KLCC"
   },
   {
    "category": "Shopping",
    "name": "Pavilion Kuala Lumpur"
   },
   {
    "category": "Business",
    "name": "Kuala Lumpur CBD & Golden Triangle Area"
   },
   {
    "category": "Landmarks",
    "name": "TRX"
   },
   {
    "category": "Landmarks",
    "name": "Merdeka 118"
   },
   {
    "category": "Healthcare",
    "name": "Nearby Hospitals"
   },
   {
    "category": "Education",
    "name": "Nearby Schools & Colleges"
   }
  ]
 },
 "alora-residence": {
  "source": "Developer sales kit (2026-09-03)",
  "keyFeatures": [],
  "facilities": [
   "Level 1",
   "items: ['Signature Retail Shops']",
   "Level 10",
   "items: ['Grill & Feast'",
   "'Dewdrop Pavilion'",
   "'Horizon Pool'",
   "'Fun Outdoor Zone'",
   "'Treetop Adventure'",
   "'Splash Pool'",
   "'Playtopia'",
   "'Callisthenics Lawn'",
   "'Herb Garden'",
   "'Crescent Bay'",
   "'Green Tier'",
   "'Rainwater Cascade'",
   "'Sun Lounge'",
   "'Changing Room']",
   "Rooftop (Level 38 & 43)",
   "items: ['Multipurpose Hall'",
   "'Bonding Pods'",
   "'Sky Gym'",
   "'Serene Garden'",
   "'Aromatic Garden'",
   "'Book Nook'",
   "'Co-working Space'",
   "'Sauna'",
   "'Sky Lounge'",
   "'Dawnlight Terrace'",
   "'Twilight Terrace'"
  ],
  "nearby": [
   {
    "category": "Public Transport",
    "name": "USJ 21 LRT Station",
    "distance": "0.3km"
   },
   {
    "category": "Public Transport",
    "name": "Sultan Abdul Aziz Shah Airport"
   },
   {
    "category": "Public Transport",
    "name": "KLIA",
    "distance": "38km"
   },
   {
    "category": "Highways",
    "name": "LDP, ELITE, KESAS, NPE, Federal Highway"
   },
   {
    "category": "Shopping",
    "name": "Main Place Mall",
    "distance": "2km"
   },
   {
    "category": "Shopping",
    "name": "Taipan Business Centre",
    "distance": "4km"
   },
   {
    "category": "Shopping",
    "name": "Bandar Sunway (Sunway Pyramid)",
    "distance": "7.3km"
   },
   {
    "category": "Shopping",
    "name": "Bandar Puteri Puchong",
    "distance": "7.5km"
   },
   {
    "category": "Education",
    "name": "SEGI College, Taylor's College, Monash University, Sunway University, INTI College"
   },
   {
    "category": "Healthcare",
    "name": "Sunway Medical Centre, Subang Jaya Medical Centre"
   },
   {
    "category": "Recreation",
    "name": "Pet-Friendly Neighbourhood Park"
   }
  ]
 },
 "aldenz": {
  "source": "Developer sales kit (2026-08-30)",
  "keyFeatures": [
   "Colonial-inspired architecture in Damansara Perdana",
   "GreenRE Certified eco-responsible development",
   "Pet-friendly concept with designated areas",
   "Diverse layouts from 775 sqft (2R2B) to 926 sqft (3R2B)",
   "Maximum 18 units per floor served by 6+1 lifts",
   "Proximity to Trader's Market, China-inspired retail street, and major highways (LDP, DASH, Penchala Link)",
   "Comprehensive facilities across Ground, Podium, and Rooftop levels."
  ],
  "facilities": [
   "Play Area",
   "Lushscape Plaza",
   "Reflex Path",
   "Aldenz Lounge",
   "The Fountain Court",
   "Flow Studio",
   "Fitness Loft",
   "Oasis Deck",
   "Bubbly Bliss (Jacuzzi)",
   "Active Park",
   "Sunset Retreat",
   "Little Ripple Bay",
   "Aldenz Oasis (Pool)",
   "Shade Alcove",
   "Games Coliseum",
   "Karaoke Vault",
   "Kiddos Kingdom",
   "Joyful Playground",
   "Garden Nook",
   "Hoop Court",
   "Yoga Alcove",
   "Furry Friends Park",
   "Herbs Haven",
   "Grill Alcove",
   "BBQ Area",
   "Yoga/ Taichi Area",
   "Outdoor Fitness"
  ],
  "nearby": [
   {
    "category": "Highways",
    "name": "Lebuhraya Damansara-Puchong (LDP)"
   },
   {
    "category": "Highways",
    "name": "SPRINT Highway"
   },
   {
    "category": "Highways",
    "name": "Penchala Link"
   },
   {
    "category": "Highways",
    "name": "DASH Highway"
   },
   {
    "category": "Public Transport",
    "name": "MRT Mutiara Damansara (SBK08)",
    "distance": "1.7km"
   },
   {
    "category": "Public Transport",
    "name": "MRT Bandar Utama (SBK09)",
    "distance": "3.3km"
   },
   {
    "category": "Public Transport",
    "name": "LRT Kelana Jaya (KJ24)",
    "distance": "8.1km"
   },
   {
    "category": "Shopping Malls",
    "name": "The Curve / IKEA",
    "distance": "3.2km"
   },
   {
    "category": "Shopping Malls",
    "name": "1 Utama Shopping Centre",
    "distance": "3.5km"
   },
   {
    "category": "Shopping Malls",
    "name": "The Starling Mall",
    "distance": "4.8km"
   },
   {
    "category": "Shopping Malls",
    "name": "Publika Shopping Gallery",
    "distance": "9.4km"
   },
   {
    "category": "Shopping Malls",
    "name": "Mid Valley & The Gardens Mall",
    "distance": "12.4km"
   },
   {
    "category": "Education",
    "name": "SJK(C) Puay Chai 2",
    "distance": "3km"
   },
   {
    "category": "Education",
    "name": "SMK & SK Bandar Utama Damansara 4",
    "distance": "3.2km"
   },
   {
    "category": "Education",
    "name": "The British International School of Kuala Lumpur",
    "distance": "4.4km"
   },
   {
    "category": "Education",
    "name": "First City University",
    "distance": "4.4km"
   },
   {
    "category": "Education",
    "name": "KDU College",
    "distance": "5.6km"
   },
   {
    "category": "Education",
    "name": "HELP University",
    "distance": "10.9km"
   },
   {
    "category": "Healthcare",
    "name": "KPJ Damansara 2",
    "distance": "1.2km"
   },
   {
    "category": "Healthcare",
    "name": "KPJ Damansara Specialist Hospital",
    "distance": "4.4km"
   },
   {
    "category": "Healthcare",
    "name": "University Malaya Medical Centre",
    "distance": "8.8km"
   }
  ]
 },
 "d-evia": {
  "source": "Developer sales kit (2026-08-30)",
  "keyFeatures": [
   "Strategic Location (Kwasa Damansara)",
   "High Connectivity with major highways",
   "Public Transport Integration (600m to MRT Kwasa Sentral)",
   "Strong Developer Reputation – EXSIM",
   "Full Lifestyle Facilities",
   "Variety of layout sizes (657 - 1109 sqft)",
   "Hassle-free home ownership with zero down payment",
   "Modern facade design by Tan’ck Architect",
   "Future Growth Potential in a new township",
   "First-Mover Advantage in the area"
  ],
  "facilities": [
   "Reading Area",
   "Tadika",
   "Musollah",
   "Islamic Mortuary Room",
   "Guardhouse",
   "Half Basketball Court / Futsal Shooting Court",
   "Waiting Lounge",
   "Reading Lounge",
   "Co-Working Space",
   "Management Office",
   "Laundry",
   "Landscape Deck",
   "Kids Playground",
   "BBQ Area",
   "Herb Garden",
   "Outdoor Gym",
   "Games Room",
   "Gymnasium",
   "Multipurpose Hall",
   "Swimming Pool",
   "Kids Pool",
   "Changing Room",
   "24-hour Security with Access Card System",
   "CCTV",
   "Landscaping"
  ],
  "nearby": [
   {
    "category": "Public Transport",
    "name": "MRT Kwasa Sentral",
    "distance": "0.6km"
   },
   {
    "category": "Public Transport",
    "name": "MRT Kwasa Damansara"
   },
   {
    "category": "Highway",
    "name": "Guthrie Corridor Expressway (GCE)"
   },
   {
    "category": "Highway",
    "name": "North Klang Valley Expressway (NKVE)"
   },
   {
    "category": "Highway",
    "name": "Damansara Shah Alam Elevated Expressway (DASH)"
   },
   {
    "category": "Highway",
    "name": "Lebuhraya Damansara Puchong (LDP)"
   },
   {
    "category": "Shopping Mall",
    "name": "Sunway Giza Mall",
    "distance": "3.2km"
   },
   {
    "category": "Shopping Mall",
    "name": "IOI Mall Damansara",
    "distance": "3.6km"
   },
   {
    "category": "Shopping Mall",
    "name": "The Curve",
    "distance": "5km"
   },
   {
    "category": "Shopping Mall",
    "name": "1 Utama Shopping Centre",
    "distance": "5.9km"
   },
   {
    "category": "Shopping Mall",
    "name": "Citta Mall",
    "distance": "6.2km"
   },
   {
    "category": "Hospital",
    "name": "Thomson Hospital Kota Damansara",
    "distance": "2.3km"
   },
   {
    "category": "Hospital",
    "name": "Hospital Sungai Buloh",
    "distance": "6.2km"
   },
   {
    "category": "Education",
    "name": "SJK (TAMIL) RRI SG BULOH School",
    "distance": "0.8km"
   },
   {
    "category": "Education",
    "name": "SK Seksyen 7 Kota Damansara",
    "distance": "0.9km"
   },
   {
    "category": "Education",
    "name": "Sri KDU Schools",
    "distance": "2.1km"
   },
   {
    "category": "Education",
    "name": "Help University & International School",
    "distance": "2.3km"
   },
   {
    "category": "Education",
    "name": "Segi University",
    "distance": "2.3km"
   }
  ]
 },
 "atera": {
  "source": "Developer sales kit (2026-09-05)",
  "keyFeatures": [
   "Transit-oriented development (TOD)",
   "400m to Asia Jaya LRT via a covered walkway",
   "Built-up options from 775 - 1,420 sq. ft",
   "Up to 4 rooms, 3 bathrooms",
   "61 holistic lifestyle facilities",
   "Equipped with Smart Home features",
   "Semi-furnished interiors",
   "Multi-tier security offerings",
   "GreenRE Silver certified"
  ],
  "facilities": [
   "Multipurpose Hall",
   "Outdoor Shower",
   "Jacuzzi",
   "Wet Deck",
   "Swimming Pool",
   "Kids' Waterplay",
   "Floating Pavilion",
   "Kickabout Area",
   "Adventure Playground",
   "Signature Water Feature",
   "Outdoor Fitness Station",
   "Reflexology Path",
   "Garden of Serenity",
   "Climbing Wall",
   "BBQ Zone",
   "Mini Bowling Lane",
   "Jogging Track",
   "Yoga Space",
   "Tai Chi Space",
   "Pre-function Space",
   "Outdoor CrossFit Area",
   "Casual Seating Lane",
   "Function Room",
   "Co-working Lounge",
   "Management Office",
   "Open Lounge",
   "Indoor Game Room",
   "Gymnasium",
   "Common Toilet",
   "Mini Cinema",
   "Surau",
   "Lift Lobby",
   "Jogging Trail",
   "Pool Pavilion",
   "Dry Deck",
   "Kid's Pool",
   "Pavilion",
   "Multi-sensory Garden",
   "Basketball Court",
   "Open Event Lawn"
  ],
  "nearby": [
   {
    "category": "Transportation",
    "name": "Asia Jaya LRT Station"
   },
   {
    "category": "Highway",
    "name": "Federal Highway"
   },
   {
    "category": "Highway",
    "name": "Damansara-Puchong Expressway (LDP)"
   },
   {
    "category": "Highway",
    "name": "SPRINT Expressway"
   },
   {
    "category": "Highway",
    "name": "New Pantai Expressway (NPE)"
   },
   {
    "category": "Highway",
    "name": "New Klang Valley Expressway (NKVE)"
   },
   {
    "category": "Shopping Mall",
    "name": "Jaya One"
   },
   {
    "category": "Shopping Mall",
    "name": "Amcorp Mall"
   },
   {
    "category": "Shopping Mall",
    "name": "KL Gateway Mall"
   },
   {
    "category": "Shopping Mall",
    "name": "Mid Valley Megamall"
   },
   {
    "category": "Shopping Mall",
    "name": "Atria Shopping Gallery"
   },
   {
    "category": "Shopping Mall",
    "name": "Bangsar Village"
   },
   {
    "category": "Hypermarket",
    "name": "AEON BiG"
   },
   {
    "category": "Hypermarket",
    "name": "Giant Supermarket Kelana Jaya"
   },
   {
    "category": "Hospital",
    "name": "Columbia Asia Hospital"
   },
   {
    "category": "Hospital",
    "name": "Tun Hussein Onn National Eye Hospital"
   },
   {
    "category": "Hospital",
    "name": "University of Malaya Medical Centre"
   },
   {
    "category": "Hospital",
    "name": "UM Specialist Centre",
    "distance": "UMSC"
   },
   {
    "category": "Hospital",
    "name": "Beacon Hospital"
   },
   {
    "category": "Hospital",
    "name": "Assunta Hospital PJ"
   },
   {
    "category": "Hospital",
    "name": "Pantai Hospital KL"
   },
   {
    "category": "Education",
    "name": "University of Malaya"
   },
   {
    "category": "Education",
    "name": "IACT College"
   },
   {
    "category": "Education",
    "name": "City University Malaysia"
   },
   {
    "category": "Education",
    "name": "Saito University College"
   },
   {
    "category": "Education",
    "name": "Heritage PJ International School"
   },
   {
    "category": "Education",
    "name": "MAZ International School"
   },
   {
    "category": "Recreational Park",
    "name": "Taman Jaya Park"
   },
   {
    "category": "Recreational Park",
    "name": "Bukit Gasing"
   }
  ]
 },
 "parkside-residence": {
  "source": "Developer sales kit (2026-08-10)",
  "keyFeatures": [],
  "facilities": [
   "Parkside Boulevard",
   "Parkside Retreat",
   "Parkside Collective",
   "Parkside Sky"
  ],
  "nearby": [
   {
    "category": "Public Transport",
    "name": "Bangsar LRT Station"
   },
   {
    "category": "Public Transport",
    "name": "KL Sentral Transport Hub"
   },
   {
    "category": "Public Transport",
    "name": "Abdullah Hukum Integrated LRT & KTM Station"
   },
   {
    "category": "Shopping Malls",
    "name": "Mid Valley City",
    "distance": "Mid Valley Megamall & The Gardens Mall"
   },
   {
    "category": "Shopping Malls",
    "name": "Nu Sentral"
   },
   {
    "category": "Shopping Malls",
    "name": "Bangsar Village"
   },
   {
    "category": "Shopping Malls",
    "name": "Bangsar Shopping Centre"
   },
   {
    "category": "Healthcare",
    "name": "Pantai Hospital Kuala Lumpur"
   },
   {
    "category": "Healthcare",
    "name": "University Malaya Medical Centre"
   },
   {
    "category": "Schools & Universities",
    "name": "University of Malaya"
   },
   {
    "category": "Schools & Universities",
    "name": "Havil International School"
   },
   {
    "category": "Schools & Universities",
    "name": "Alice Smith International School Primary Campus"
   },
   {
    "category": "Parks & Recreation",
    "name": "Perdana Botanical Garden"
   },
   {
    "category": "Parks & Recreation",
    "name": "KL Bird Park"
   }
  ]
 },
 "menerung": {
  "source": "Developer sales kit (2026-08-12)",
  "keyFeatures": [
   "Prime location in Bangsar",
   "Low density with only 111 exclusive suites",
   "Freehold tenure",
   "Walking distance to Bangsar Shopping Centre and Pusat Bandar Damansara MRT",
   "Comprehensive rooftop facilities",
   "High-quality finishes and partial furnishing",
   "Developed by reputable developer BRDB"
  ],
  "facilities": [
   "Lift Lobby",
   "Swimming Pool",
   "Wading Pool",
   "Jacuzzi",
   "BBQ Terrace",
   "Changing Room / Washroom",
   "Rooftop Gardens",
   "Gymnasium",
   "Surau",
   "Multipurpose Hall",
   "Sculpture Garden",
   "Gravel Garden",
   "Lawn",
   "Viewing Terrace",
   "Lobby"
  ],
  "nearby": [
   {
    "category": "Shopping & Retail",
    "name": "Bangsar Shopping Centre (BSC)"
   },
   {
    "category": "Shopping & Retail",
    "name": "Bangsar Village"
   },
   {
    "category": "Shopping & Retail",
    "name": "Pavilion Damansara Heights"
   },
   {
    "category": "Shopping & Retail",
    "name": "Publika Shopping Gallery"
   },
   {
    "category": "Shopping & Retail",
    "name": "Plaza Batai"
   },
   {
    "category": "Shopping & Retail",
    "name": "Plaza Damansara"
   },
   {
    "category": "Shopping & Retail",
    "name": "Jalan Telawi commercial area"
   },
   {
    "category": "Shopping & Retail",
    "name": "Central Market"
   },
   {
    "category": "Public Transportation",
    "name": "Pusat Bandar Damansara MRT Station"
   },
   {
    "category": "Highways",
    "name": "SPRINT Expressway"
   },
   {
    "category": "Highways",
    "name": "Lebuhraya Mahameru"
   },
   {
    "category": "Education",
    "name": "Garden International School', \"Mont' Kiara International School"
   },
   {
    "category": "Medical",
    "name": "Pantai Hospital Kuala Lumpur"
   },
   {
    "category": "Medical",
    "name": "Global Doctors Hospital"
   },
   {
    "category": "Recreation & Leisure",
    "name": "Bukit Kiara Park"
   },
   {
    "category": "Recreation & Leisure",
    "name": "TPC Kuala Lumpur (Golf Club)"
   },
   {
    "category": "Recreation & Leisure",
    "name": "Bukit Kiara Equestrian & Country Resort"
   },
   {
    "category": "Recreation & Leisure",
    "name": "Royal Selangor Club"
   },
   {
    "category": "Recreation & Leisure",
    "name": "National Science Centre"
   },
   {
    "category": "Recreation & Leisure",
    "name": "Perdana Botanical Garden (Tasik Perdana)"
   },
   {
    "category": "Landmarks",
    "name": "National Palace (Istana Negara)"
   },
   {
    "category": "Landmarks",
    "name": "Parliament of Malaysia"
   },
   {
    "category": "Landmarks",
    "name": "National Mosque of Malaysia"
   }
  ]
 },
 "stellaris-riana-dutamas": {
  "source": "Developer sales kit (2026-08-11)",
  "keyFeatures": [],
  "facilities": [
   "Panoramic Terrace",
   "Multi-Purpose Hall",
   "Co-Working Space",
   "Games Room",
   "Convenience Shop (provision)",
   "Kiddy Playland",
   "Indoor Lounge",
   "Sun Deck",
   "Spa Pool",
   "Zen Pavillion",
   "Wading Pool",
   "Elevated Infinity Pool",
   "Floating Deck",
   "Changing Room",
   "Sauna",
   "Children Playground",
   "Function Room",
   "Herb Garden",
   "Barbecue Terrace",
   "Mini Golf",
   "Stroll and Jog Trail",
   "Outdoor Fitness Station",
   "Outdoor Lounge",
   "Yoga Deck",
   "Reflexology Path",
   "Gym",
   "Dance Studio"
  ],
  "nearby": [
   {
    "category": "Transport",
    "name": "Segambut KTM Station"
   },
   {
    "category": "Transport",
    "name": "DUKE Highway"
   },
   {
    "category": "Transport",
    "name": "DUKE 2 Highway"
   },
   {
    "category": "Transport",
    "name": "NKVE Highway"
   },
   {
    "category": "Transport",
    "name": "SPRINT Highway"
   },
   {
    "category": "Transport",
    "name": "PLUS Highway"
   },
   {
    "category": "Shopping",
    "name": "Publika Shopping Gallery"
   },
   {
    "category": "Shopping",
    "name": "United Point Mall"
   },
   {
    "category": "Shopping",
    "name": "Solaris Mont Kiara"
   },
   {
    "category": "Shopping",
    "name": "World Trade Centre Kuala Lumpur (PWTC)"
   },
   {
    "category": "Shopping",
    "name": "Suria KLCC"
   },
   {
    "category": "Shopping",
    "name": "Pavilion Kuala Lumpur"
   },
   {
    "category": "Education",
    "name": "SMK Segambut"
   },
   {
    "category": "Education",
    "name": "SRJK (C) Khai Chee"
   },
   {
    "category": "Education",
    "name": "Garden International School"
   },
   {
    "category": "Education",
    "name": "Mont'Kiara International School"
   },
   {
    "category": "Education",
    "name": "HELP University"
   },
   {
    "category": "Healthcare",
    "name": "A Plus Medical Clinic"
   },
   {
    "category": "Healthcare",
    "name": "Klinik Kiara Segambut"
   },
   {
    "category": "Healthcare",
    "name": "ParkCity Medical Centre"
   },
   {
    "category": "Healthcare",
    "name": "KPJ Tawakkal Hospital"
   },
   {
    "category": "Healthcare",
    "name": "Hospital Kuala Lumpur"
   },
   {
    "category": "Healthcare",
    "name": "Institut Jantung Negara (IJN)"
   }
  ]
 },
 "pavilion-square-residences": {
  "source": "Developer sales kit (2026-08-13)",
  "keyFeatures": [
   "Exclusive location with dedicated linked-bridge connected to Pavilion Kuala Lumpur",
   "Unit types ranging from studio to 3BR, flexible for own-stay and investment",
   "Highest & Longest Swimming pool (118 metre) in KL City Centre",
   "Highest & Largest Sky sports zone (15,000sf) in KL City Centre",
   "Established neighbourhood surrounded by Hotels, Hospitals, International Schools, Embassies, Shopping malls, Restaurants & Entertainment."
  ],
  "facilities": [
   "Concierge Lobby",
   "Reading Room",
   "KTV Room",
   "Club Lounge",
   "Entertainment Room",
   "Business Center",
   "Laundromat",
   "Kid's Room",
   "BBQ Plaza",
   "Outdoor Lounge",
   "Open Lawn",
   "Courtyard Garden",
   "Sky Wellness Zone (15",
   "000 sq.ft.)",
   "Gymnasium",
   "Outdoor Gym",
   "Steam Room",
   "Sauna",
   "Changing Room",
   "Sports Lounge",
   "Sky Garden",
   "118-metre Rooftop Infinity Sky Pool",
   "Kids' Pool",
   "Wading Pool",
   "Jacuzzi Pool",
   "Pool Deck"
  ],
  "nearby": [
   {
    "category": "Shopping Malls",
    "name": "Pavilion Kuala Lumpur (via dedicated link-bridge)"
   },
   {
    "category": "Shopping Malls",
    "name": "Suria KLCC"
   },
   {
    "category": "Shopping Malls",
    "name": "The Starhill"
   },
   {
    "category": "Shopping Malls",
    "name": "Fahrenheit88"
   },
   {
    "category": "Shopping Malls",
    "name": "Lot 10"
   },
   {
    "category": "Shopping Malls",
    "name": "Sungei Wang"
   },
   {
    "category": "Shopping Malls",
    "name": "Berjaya Times Square"
   },
   {
    "category": "Shopping Malls",
    "name": "Lalaport Bukit Bintang City Centre"
   },
   {
    "category": "Transportation",
    "name": "Bukit Bintang MRT Station"
   },
   {
    "category": "Transportation",
    "name": "Conlay MRT Station"
   },
   {
    "category": "Transportation",
    "name": "Bukit Bintang Monorail Station"
   },
   {
    "category": "Transportation",
    "name": "Raja Chulan Monorail Station"
   },
   {
    "category": "Transportation",
    "name": "Bukit Bintang – KLCC Pedestrian Walkway"
   },
   {
    "category": "Healthcare",
    "name": "Prince Court Medical Centre"
   },
   {
    "category": "Healthcare",
    "name": "Tung Shin Hospital"
   },
   {
    "category": "Healthcare",
    "name": "Kuala Lumpur Hospital"
   },
   {
    "category": "Healthcare",
    "name": "Gleneagles Hospital Kuala Lumpur"
   },
   {
    "category": "Landmarks",
    "name": "Petronas Twin Towers (KLCC)"
   },
   {
    "category": "Landmarks",
    "name": "KL Tower"
   },
   {
    "category": "Landmarks",
    "name": "Tun Razak Exchange (TRX)"
   },
   {
    "category": "Landmarks",
    "name": "Merdeka 118"
   },
   {
    "category": "Recreation",
    "name": "Royal Selangor Golf Club (RSGC)"
   },
   {
    "category": "Recreation",
    "name": "KLCC Park"
   },
   {
    "category": "Recreation",
    "name": "KL Forest Eco Park"
   },
   {
    "category": "Hotels",
    "name": "Pavilion Hotel"
   },
   {
    "category": "Hotels",
    "name": "Banyan Tree Kuala Lumpur"
   },
   {
    "category": "Hotels",
    "name": "JW Marriott Hotel Kuala Lumpur"
   },
   {
    "category": "Hotels",
    "name": "The Westin Kuala Lumpur"
   },
   {
    "category": "Hotels",
    "name": "Ritz-Carlton Kuala Lumpur"
   }
  ]
 },
 "pavilion-square-office": {
  "source": "Developer sales kit (2026-08-13)",
  "keyFeatures": [
   "Exclusive location with dedicated linked-bridge connected to Pavilion Kuala Lumpur",
   "Unit types ranging from studio to 3BR, flexible for own-stay and investment",
   "Highest & Longest Swimming pool (118 metre) in KL City Centre",
   "Highest & Largest Sky sports zone (15,000sf) in KL City Centre",
   "Established neighbourhood surrounded by Hotels, Hospitals, International Schools, Embassies, Shopping malls, Restaurants & Entertainment."
  ],
  "facilities": [
   "Concierge Lobby",
   "Reading Room",
   "KTV Room",
   "Club Lounge",
   "Entertainment Room",
   "Business Center",
   "Laundromat",
   "Kid's Room",
   "BBQ Plaza",
   "Outdoor Lounge",
   "Open Lawn",
   "Courtyard Garden",
   "Sky Wellness Zone (15",
   "000 sq.ft.)",
   "Gymnasium",
   "Outdoor Gym",
   "Steam Room",
   "Sauna",
   "Changing Room",
   "Sports Lounge",
   "Sky Garden",
   "118-metre Rooftop Infinity Sky Pool",
   "Kids' Pool",
   "Wading Pool",
   "Jacuzzi Pool",
   "Pool Deck"
  ],
  "nearby": [
   {
    "category": "Shopping Malls",
    "name": "Pavilion Kuala Lumpur (via dedicated link-bridge)"
   },
   {
    "category": "Shopping Malls",
    "name": "Suria KLCC"
   },
   {
    "category": "Shopping Malls",
    "name": "The Starhill"
   },
   {
    "category": "Shopping Malls",
    "name": "Fahrenheit88"
   },
   {
    "category": "Shopping Malls",
    "name": "Lot 10"
   },
   {
    "category": "Shopping Malls",
    "name": "Sungei Wang"
   },
   {
    "category": "Shopping Malls",
    "name": "Berjaya Times Square"
   },
   {
    "category": "Shopping Malls",
    "name": "Lalaport Bukit Bintang City Centre"
   },
   {
    "category": "Transportation",
    "name": "Bukit Bintang MRT Station"
   },
   {
    "category": "Transportation",
    "name": "Conlay MRT Station"
   },
   {
    "category": "Transportation",
    "name": "Bukit Bintang Monorail Station"
   },
   {
    "category": "Transportation",
    "name": "Raja Chulan Monorail Station"
   },
   {
    "category": "Transportation",
    "name": "Bukit Bintang – KLCC Pedestrian Walkway"
   },
   {
    "category": "Healthcare",
    "name": "Prince Court Medical Centre"
   },
   {
    "category": "Healthcare",
    "name": "Tung Shin Hospital"
   },
   {
    "category": "Healthcare",
    "name": "Kuala Lumpur Hospital"
   },
   {
    "category": "Healthcare",
    "name": "Gleneagles Hospital Kuala Lumpur"
   },
   {
    "category": "Landmarks",
    "name": "Petronas Twin Towers (KLCC)"
   },
   {
    "category": "Landmarks",
    "name": "KL Tower"
   },
   {
    "category": "Landmarks",
    "name": "Tun Razak Exchange (TRX)"
   },
   {
    "category": "Landmarks",
    "name": "Merdeka 118"
   },
   {
    "category": "Recreation",
    "name": "Royal Selangor Golf Club (RSGC)"
   },
   {
    "category": "Recreation",
    "name": "KLCC Park"
   },
   {
    "category": "Recreation",
    "name": "KL Forest Eco Park"
   },
   {
    "category": "Hotels",
    "name": "Pavilion Hotel"
   },
   {
    "category": "Hotels",
    "name": "Banyan Tree Kuala Lumpur"
   },
   {
    "category": "Hotels",
    "name": "JW Marriott Hotel Kuala Lumpur"
   },
   {
    "category": "Hotels",
    "name": "The Westin Kuala Lumpur"
   },
   {
    "category": "Hotels",
    "name": "Ritz-Carlton Kuala Lumpur"
   }
  ]
 },
 "golden-crown": {
  "source": "Developer sales kit (2026-08-29)",
  "keyFeatures": [
   "Transit Oriented Development (TOD) with direct underground connection to TRX MRT station & mall",
   "Located in the heart of Kuala Lumpur, adjacent to Tun Razak Exchange (TRX)",
   "Part of Menara Golden Eagle, a mixed-use development with residence, hotel, and office",
   "Modern luxury residence with comprehensive rooftop facilities."
  ],
  "facilities": [
   "Concierge",
   "24-hr Security",
   "Kindergarten",
   "Lobby",
   "Retail",
   "Management Office",
   "Mail Room",
   "Retail & Tunnel to TRX MRT 1&2 Interchange",
   "Prayer Room",
   "Library",
   "Gym Room",
   "Multi-Purpose Room",
   "Games/Video Room",
   "Infinity Swimming Pool",
   "Wading Pool",
   "Pool Deck",
   "BBQ Terrace",
   "Children Playground",
   "F/M Changing Room"
  ],
  "nearby": [
   {
    "category": "Nearby",
    "name": "Public Transportation: MRT Line 1 & 2 Transit (50m), MRT tunnel connection to TRX MRT interchange"
   },
   {
    "category": "Nearby",
    "name": "Shopping Malls: The Exchange TRX (50m), IKEA / MyTown (800m), Berjaya Times Squares (900m), Pavilion KL / Starhill / Lot 10 (1.0km), Suria KLCC",
    "distance": "1.8km"
   },
   {
    "category": "Nearby",
    "name": "Medical Centres: Prince Court Medical Centre (600m), Tung Shin Hospital (800m), HSC Medical Center",
    "distance": "2.0km"
   },
   {
    "category": "Nearby",
    "name": "Leisure and Parks: TRX 10 acres park (50m), Royal Selangor Golf Club (550m), KLCC Park",
    "distance": "1.3km"
   },
   {
    "category": "Nearby",
    "name": "Schools: EtonHouse International School (1.0km), Tsun Jin Chinese High School (1.8km), International School of Kuala Lumpur (ISKL)",
    "distance": "2.3km"
   },
   {
    "category": "Nearby",
    "name": "Highways: Jalan Tun Razak, SMART Tunnel, MEX Highway, SPE Highway"
   }
  ]
 },
 "centrix": {
  "source": "Developer sales kit (2026-08-28)",
  "keyFeatures": [
   "A 47-storey TOD (Transit-Oriented Development) rising above Dang Wangi LRT Station",
   "Strategically located at the intersection of Jalan Ampang and Jalan Sultan Ismail",
   "Exclusive, modern cityscape facilities on the 10th and 45th podium levels",
   "Smart investment options for short-term and long-term rental."
  ],
  "facilities": [
   "Retail",
   "Grand Lobby & reception area",
   "Orchestra Garden",
   "Riverie Garden",
   "Rhapsody Water Cascades",
   "Misty Alcoves",
   "Tune Trails",
   "Harmony Canopy",
   "Mini Lawn",
   "Tangerine Cloister",
   "Harmonia Bar",
   "Crescendo Garden",
   "Chime Swings",
   "Birds Chirping Plays",
   "Flexible meeting rooms",
   "Fully serviced workspaces",
   "Dedicated lounges",
   "Games room",
   "Reading room",
   "Gourmet kitchen",
   "Sonata Verde",
   "Melodic Sun Deck",
   "Kids Pool (5.5m X 4.5m, depth 600mm)",
   "Aqua Sonata Pools (16m X 4.5m, depth 1.2m)",
   "Tango Cabanas",
   "Sky Views",
   "BBQ Garden",
   "Sky Gymnasium",
   "Sky Lounge"
  ],
  "nearby": [
   {
    "category": "Public Transport",
    "name": "Dang Wangi LRT Station (KJ12)"
   },
   {
    "category": "Public Transport",
    "name": "Bukit Nanas Monorail Station"
   },
   {
    "category": "Landmark & Entertainment",
    "name": "KL Forest Eco Park"
   },
   {
    "category": "Landmark & Entertainment",
    "name": "Quill City Mall"
   },
   {
    "category": "Landmark & Entertainment",
    "name": "Life Centre"
   },
   {
    "category": "Landmark & Entertainment",
    "name": "Saloma Link"
   },
   {
    "category": "Landmark & Entertainment",
    "name": "Petronas Twin Tower / Suria KLCC"
   },
   {
    "category": "Landmark & Entertainment",
    "name": "Avenue K"
   },
   {
    "category": "Landmark & Entertainment",
    "name": "KL Tower"
   },
   {
    "category": "Landmark & Entertainment",
    "name": "Pavilion Shopping Gallery"
   },
   {
    "category": "Landmark & Entertainment",
    "name": "Merdeka 118"
   },
   {
    "category": "Landmark & Entertainment",
    "name": "The Exchange TRX"
   },
   {
    "category": "Education",
    "name": "St John International"
   },
   {
    "category": "Education",
    "name": "Primerose Hill International"
   },
   {
    "category": "Education",
    "name": "Eton International"
   },
   {
    "category": "Hospital/Medical",
    "name": "KPJ Sentosa"
   },
   {
    "category": "Hospital/Medical",
    "name": "Prince Court Medical Centre"
   },
   {
    "category": "Hospital/Medical",
    "name": "HSC Medical Centre"
   }
  ]
 },
 "kingswoodz-bukit-jalil": {
  "source": "Developer sales kit (2026-08-06)",
  "keyFeatures": [
   "Great accessibility & connectivity within a close proximity to amenities & public transport",
   "Surrounded by matured neighbourhood with shopping malls, banks, schools and universities",
   "Full facilities with mixed concepts (Dynamic, Leisure, Relaxing Zone)",
   "Hassle-free home ownership with low down payment, all units come standard partially furnished",
   "Modern facade design by WDA Design",
   "Multi-generational layouts for first home buyers and downsizers."
  ],
  "facilities": [
   "Skyline Sip (Sky Lounge)",
   "Sky Barbeque",
   "Sky Nourish Dining",
   "Sky Greenery Galore (Sky Garden)"
  ],
  "nearby": [
   {
    "category": "Public Transport",
    "name": "LRT Awan Besar (SP19)",
    "distance": "0.9km"
   },
   {
    "category": "Public Transport",
    "name": "Rapid KL Bus Stop KL1743 Green Avenue Condominium (Route T580)",
    "distance": "0.23km"
   },
   {
    "category": "Highways",
    "name": "KESAS Highway"
   },
   {
    "category": "Highways",
    "name": "Lebuhraya NPE (Kuchai Link)"
   },
   {
    "category": "Highways",
    "name": "Maju Expressway",
    "distance": "MEX"
   },
   {
    "category": "Highways",
    "name": "Sprint Highway"
   },
   {
    "category": "Highways",
    "name": "ELITE Expressway"
   },
   {
    "category": "Highways",
    "name": "Sungai Besi Expressway"
   },
   {
    "category": "Highways",
    "name": "Sungai Besi - Ulu Kelang Expressway (SUKE)"
   },
   {
    "category": "Shopping & Groceries",
    "name": "Aurora Place Bukit Jalil",
    "distance": "1km"
   },
   {
    "category": "Shopping & Groceries",
    "name": "Pavilion Bukit Jalil",
    "distance": "2.8km"
   },
   {
    "category": "Shopping & Groceries",
    "name": "The Food Merchant @ Bukit Jalil",
    "distance": "3.4km"
   },
   {
    "category": "Shopping & Groceries",
    "name": "Giant Hypermarket @ Bukit Kinrara",
    "distance": "5.2km"
   },
   {
    "category": "Shopping & Groceries",
    "name": "NSK Trade City @ Kuchai Lama",
    "distance": "6.6km"
   },
   {
    "category": "Shopping & Groceries",
    "name": "Mid Valley Megamall",
    "distance": "7.5km"
   },
   {
    "category": "Education",
    "name": "SJK(C) Lai Meng",
    "distance": "1km"
   },
   {
    "category": "Education",
    "name": "SJK(T) Ladang Bukit Jalil",
    "distance": "1.5km"
   },
   {
    "category": "Education",
    "name": "International Medical University (IMU)",
    "distance": "4.4km"
   },
   {
    "category": "Education",
    "name": "Asia Pacific University of Technology & Innovation (APU)"
   },
   {
    "category": "Medical",
    "name": "KMI Taman Desa Medical Centre",
    "distance": "6.3km"
   },
   {
    "category": "Medical",
    "name": "Sunway Medical Centre",
    "distance": "8.7km"
   },
   {
    "category": "Recreation",
    "name": "Bukit Jalil Recreational Park",
    "distance": "1km"
   },
   {
    "category": "Recreation",
    "name": "Bukit Jalil Golf & Country Resort"
   }
  ]
 }
};
